/* What a Commons file title must say (and must not say) to count as a photo
 * of each product type. Stricter than the gx taxonomy's `must` lists, which
 * accept any mention in the categories: "wireless earbuds" must not take
 * over-ear headphones, "dumbbells" must not take a scanned manuscript.
 *
 * [any, not]: the title needs one of `any` (whole words, a plural s/es is
 * fine) and none of `not`. The first few `any` phrases are also the search
 * queries (intitle:"..."). Adding a type is a data edit here.
 */

const ANCIENT = ['museum', 'ancient', 'roman', 'egyptian', 'medieval', 'bronze', 'viking', 'dynasty', 'tribal', 'celtic', 'archaeolog', 'excavat', 'antique'];
const GAME = ['game', 'match', 'player', 'nba', 'league', 'team', 'tournament', 'championship', 'dunk', 'arena', 'stadium', 'cheerleader', 'coach', 'vs'];
const DRESS_NOT = ['wedding', 'bride', 'bridal', 'traditional', 'costume', 'prom', 'ball gown', 'military', 'uniform', 'ceremony', 'performance', 'dance', 'dancer', 'cosplay', 'museum', 'queen', 'princess', 'actress', 'fashion week', 'runway'];

const PEOPLE = ['woman', 'man', 'girl', 'boy', 'lady', 'senior', 'couple', 'student', 'people', 'person', 'child', 'kid', 'kids', 'children', 'using', 'works', 'working', 'typing', 'monitoring', 'portrait'];

/* Applied to every type: street and mall snapshots (the "HK ... Plaza" titles
 * are photos of a place, not a product), and a few words that mean the file
 * is not a clean product photo. */
export const GLOBAL_NOT = ['hk', 'tko', 'kowloon', 'plaza', 'mall', 'xxx', 'flickr', 'dateiname', 'screenshot', 'icon', 'logo'];


/* Files rejected by eye after reviewing every photo the first dealing chose:
 * a band named "Face Cream", astronomy and Algerian places named "Mascara",
 * puffer fish, a photographer's snapshot of a conference. Word lists cannot
 * catch these, so they are listed by Commons page id. Removing an id here and
 * re-running `npm run mx:images` puts it back in the pool. */
export const DENY_IDS = new Set([
  // Thumbnails Wikimedia kept answering HTTP 429 for after repeated tries:
  '149847889',
  '61289530',
  '50763926',
  '31060994',
  '20239158',
  '20239171',
  '115497431',
  '151200347',
  '83053523',
  '83053526',
  '83053525',
  '54037046',
  '28937730',
  '113422388',
  '64666963',
  '3786284',
  '22179260',
  '5266233',
  '7811966',
  '197080251',
  '160728028',
  '113407442',
  '32388804',
  '33334408',
  '33334217',
  '49456586',
  '49475330',
  '33334247',
  '32384391',
  '50396334',
  '32386453',
  '138694280',
  '17659832',
  '120941691',
  '156534592',
  '9521376',
  '69512689',
  '50293348',
  '180413371',
  '126924332',
  '197563525',
  '180400661',
  '85912742',
  '77983868',
  '15027435',
  '31092897',
  '31092911',
  '31092885',
  '31048849',
  '31058530',
  '31055329',
  '198225510',
  '198225514',
  '117977900',
  '117977899',
  '129452964',
  '196012951',
  '83043304',
  '2350788',
  '127527546',
  '32528391',
  '60347193',
  '62192452',
  '5572136',
  '196191086',
  '160011846',
  '142073932',
  '144722050',
  '142771128',
  '128650848',
  '196010971',
  '114515249',
  '115189278',
  '122502044',
  '82946749',
  '140673215',
  '123013027',
  '36068002',
  '50882620',
  '50882555',
  '125196677',
  '151210636',
  '36762970',
  '36762926',
  '37672929',
  '77224857',
  '5046377',
  '48267350',
  '44311599',
  '187645835',
  '160196313',
  '63811329',
  '89172773',
  '170837552',
  '80168288',
  '170733798',
  '187645844',
  '160274547',
  '59705566',
  '170733799',
  '160274552',
  '187645839',
  '8208771',
  '170837550',
  '55640684',
  '31745978',
  '66052566',
  '151623494',
  '115666477',
  '38786251',
  '100163412',
  '1576502',
  '21526232',
  '63223720',
  '200747322',
  '163497853',
  '137281085',
  '180444084',
  '151026642',
  '151026635',
  '151026644',
  '160848276',
  '8230338',
  '196950683',
  '90876435',
  '102939475',
  '159662865',
  '63941393',
  '8481033',
  '38934031',
  '38934025',
  '175526161',
  '148028677',
  '94016470',
  '162640343',
  '157924250',
  '3832432',
  '126956231',
  '6833818',
  '114333485',
  '157201303',
  '95751648',
  '178420394',
  '2032414',
  '129561028',
  '129561021',
  '17327059',
  '111423317',
  '79736642',
  '24377112',
  '32929967',
  '189982016',
  '75291368',
  '15440222',
  '15440182',
  '37123944',
  '68566867',
  '82174294',
  '11644815',
  '129176897',
  '41463099',
  '39192780',
  '64259719',
  '193807541',
  '56960507',
  '188690223',
  '112311057',
  '112311059',
  '117546896',
  '151803737',
  '122593702',
  '121835146',
  '21299801',
  '49466613',
  '122583428',
  '148687165',
  '119412631',
  '39076858',
  '88905910',
  '82416086',
  '60041739',
  '97553527',
  '71024536',
  '181560504',
  '67572769',
  '67572836',
  '47086052',
  '151231492',
  '24802403',
  '151976165',
  '151524106',
  '148291692',
  '44052610',
  '104953392',
  '104953393',
  '160012955',
  '27678013',
  '20087767',
  '60730126',
  '76198743',
  '26100297',
  '76198764',
  '24934769',
  '60730097',
  '119563458',
  '76198760',
  '60730072',
  '76198761',
  '60730106',
  '76198757',
  '60730129'
]);

export const PHOTO_TERMS = {
  earbuds: [['earbud', 'earphone', 'airpod', 'in-ear', 'earbuds'], ['over-ear', 'headband', 'store', 'shop', 'wires', 'cussion', 'cushion'].concat(['vendor', 'shenzhen', 'seller', 'sale', 'stall'])],
  headphones: [['headphone', 'headset'], ['earbud', 'airpod', 'gaming', 'call center', 'operator'].concat(PEOPLE)],
  speaker: [['bluetooth speaker', 'portable speaker', 'wireless speaker', 'smart speaker', 'jbl', 'boombox'], ['conference', 'public address', 'panel', 'keynote'].concat(PEOPLE)],
  smartphone: [['smartphone', 'iphone', 'samsung galaxy', 'galaxy', 'pixel', 'xiaomi', 'redmi', 'oneplus', 'huawei', 'nokia', 'mobile phone', 'cell phone', 'cellphone', 'android phone', 'phone'], ['accessor', 'case', 'holder', 'cart', 'seller', 'charger', 'booth', 'shop', 'store', 'repair', 'cage', 'tower', 'antenna', 'vendor', 'market', 'selfie', 'woman', 'man', 'girl', 'boy', 'using', 'taking', 'stage', 'idol', 'cosplay', 'erotic', 'screenshot', 'lady', 'people', 'student', 'photograph'].concat(PEOPLE)],
  'phone-case': [['phone case', 'smartphone case', 'iphone case', 'phone cover', 'mobile cover', 'mobile case', 'bumper case', 'case for'], ['suitcase', 'seller', 'market', 'shop', 'vendor', 'accessories']],
  'wireless-charger': [['wireless charger', 'wireless charging', 'qi charger', 'charging pad', 'charging stand', 'magsafe'], ['electric vehicle', 'car charging', 'ev charging', 'bus', 'station']],
  laptop: [['laptop', 'notebook computer', 'macbook', 'thinkpad', 'chromebook', 'ultrabook'], ['cooler', 'repair', 'sticker', 'class', 'lecture', 'conference'].concat(PEOPLE)],
  keyboard: [['keyboard'], ['piano', 'synthesizer', 'organ', 'midi', 'music', 'keyboardist', 'accordion', 'harpsichord', 'typewriter', 'onscreen', 'on-screen', 'virtual', 'layout', 'concert', 'band', 'church'].concat(PEOPLE)],
  monitor: [['computer monitor', 'lcd monitor', 'led monitor', 'ultrawide', 'monitor'], ['navy', 'army', 'air force', 'technician', 'convair', 'negative', 'graphic', 'military', 'code on', 'heart', 'baby', 'lizard', 'varanus', 'hospital', 'patient', 'vital', 'fetal', 'sleep', 'air quality', 'radiation', 'nuclear', 'ecg', 'ekg', 'blood'].concat(['disposed', 'pallet', 'dead', 'snow', 'multi-monitor', 'workstation', 'recycl', 'garbage', 'junk', 'pile', 'storage', 'old']).concat(PEOPLE)],
  mouse: [['computer mouse', 'wireless mouse', 'optical mouse', 'gaming mouse', 'logitech', 'mx master'], ['mickey', 'rodent', 'field mouse', 'house mouse'].concat(PEOPLE)],
  'action-camera': [['gopro', 'action camera', 'action cam', 'sports camera', 'dji osmo', 'insta360'], []],
  mirrorless: [['mirrorless', 'sony alpha', 'fujifilm x', 'lumix', 'canon eos r', 'nikon z', 'olympus om-d', 'sony a7', 'sony a6', 'camera body'], []],
  tripod: [['tripod'], ['fish', 'stool', 'island', 'telescope mount', 'surveying'].concat(['human', 'restaurant', 'persian', 'archaeolog', 'pompe', 'vase', 'ding', 'cauldron', 'bowl', 'sacrific'])],
  'smart-tv': [['smart tv', 'television', 'led tv', 'lcd tv', 'oled tv', 'tv set'], ['antenna', 'studio', 'broadcast', 'news', 'reporter', 'tower', 'vintage', 'crt', 'retro', 'cathode', 'remote control'].concat(PEOPLE)],
  soundbar: [['soundbar', 'sound bar'], []],
  projector: [['projector'], ['slide', 'overhead', 'film', 'cinema', 'movie', '35mm', '8mm', '16mm', 'headlight', 'magic lantern', 'planetarium', 'theatre', 'theater', 'museum'].concat(PEOPLE)],
  smartwatch: [['smartwatch', 'smart watch', 'apple watch', 'galaxy watch', 'wear os', 'pebble'], []],
  'fitness-band': [['fitness band', 'fitness tracker', 'activity tracker', 'mi band', 'fitbit', 'smart band', 'smartband'], []],
  'smart-bulb': [['light bulb', 'led bulb', 'smart bulb', 'lightbulb', 'led lamp'], ['tulip', 'flower', 'garlic', 'onion', 'daffodil', 'plant', 'museum', 'centennial', 'edison']],
  'security-camera': [['security camera', 'surveillance camera', 'cctv', 'ip camera', 'dome camera'], ['protest', 'monument', 'building', 'street', 'city']],
  'smart-plug': [['smart plug', 'power outlet', 'electrical outlet', 'power plug', 'wall plug', 'socket'], ['bath', 'sink', 'drain', 'spark', 'car', 'cpu', 'eye', 'light socket', 'ball']],
  tshirt: [['t-shirt', 'tshirt', 't shirt', 'tee shirt'], ['protest', 'rally', 'slogan']],
  hoodie: [['hoodie', 'sweatshirt', 'hooded sweatshirt'], ['protest', 'trayvon', 'rally'].concat(['circuit', 'dip-8', 'stutz', 'biennale', 'target', 'characters'])],
  'button-shirt': [['dress shirt', 'button-up', 'button up', 'button-down', 'button down', 'oxford shirt', 'collared shirt', 'formal shirt', 'linen shirt', 'flannel shirt', 'denim shirt'], ['t-shirt', 'polo', 'football', 'jersey']],
  'summer-dress': [['summer dress', 'sundress', 'dress'], DRESS_NOT],
  'maxi-dress': [['maxi dress', 'long dress', 'dress', 'gown'], DRESS_NOT],
  'wrap-dress': [['wrap dress', 'dress'], DRESS_NOT],
  'denim-jacket': [['denim jacket', 'jean jacket', 'jeans jacket', 'denim'], ['protest', 'factory', 'mill']],
  'puffer-jacket': [['puffer jacket', 'puffer coat', 'down jacket', 'padded jacket', 'winter jacket', 'parka', 'quilted jacket'], ['military', 'arctic', 'expedition'].concat(['arothron', 'fish', 'pufferfish', 'sphoeroides', 'manilensis', 'maculatus', 'meleagris', 'geograph', 'kirky', 'surname', 'locomotive', 'steam', 'mushroom', 'ball', 'pvc'])],
  'rain-jacket': [['rain jacket', 'raincoat', 'rain coat', 'waterproof jacket', 'windbreaker', 'anorak', 'poncho'], ['military', 'police', 'straw', 'peasant', 'mino', 'indigenous', 'historic', 'c. 18', 'vintage']],
  backpack: [['backpack', 'rucksack', 'knapsack'], ['military', 'soldier', 'jet', 'jetpack', 'police']],
  tote: [['tote bag', 'tote', 'canvas bag', 'shopping bag'], ['plastic bag', 'garbage', 'waste', 'protest']],
  crossbody: [['crossbody', 'cross-body', 'shoulder bag', 'sling bag', 'messenger bag', 'handbag', 'purse'], ['police', 'military', 'diplomatic', 'museum']],
  sunglasses: [['sunglass', 'sunglasses', 'shades'], ['eclipse', 'museum'].concat(PEOPLE)],
  'blue-light': [['glasses', 'eyeglass', 'spectacle', 'eyewear'], ['sun', 'safety', '3d', 'ski', 'swimming', 'goggle', 'magnif', 'telescope', 'wine', 'drinking', 'reading glasses museum']],
  serum: [['serum', 'dropper', 'face oil', 'skincare', 'skin care'], ['blood', 'antivenom', 'vaccine', 'laboratory', 'test tube', 'syringe', 'albumin', 'anti'].concat(['rockharz', 'festival', 'ballenstedt', 'concert', 'band'])],
  moisturizer: [['moisturizer', 'moisturiser', 'face cream', 'skin cream', 'body lotion', 'hand cream', 'cream jar'], ['ice cream', 'sour cream', 'whipped', 'shaving', 'cream cheese']],
  sunscreen: [['sunscreen', 'sunblock', 'sun cream', 'sun lotion', 'suncream', 'spf'], []],
  cleanser: [['cleanser', 'face wash', 'facial wash', 'facial cleanser', 'face soap', 'cleansing'], ['dish', 'toilet', 'car', 'floor', 'oven', 'cleansing of'].concat(['mine', 'canyon', 'dutch', 'denture', 'toilet', 'toner'])],
  lipstick: [['lipstick', 'lip stick'], ['bite', 'kabuki', 'drag'].concat(['plant', 'jungle', 'building', 'band', 'applies', 'lesbian', 'tumbler'])],
  foundation: [['liquid foundation', 'foundation makeup', 'makeup foundation', 'foundation cream', 'compact powder', 'face powder', 'beauty blender', 'concealer', 'bb cream'], ['stage', 'theatre', 'theater', 'clown', 'kabuki', 'drag', 'cosplay', 'performer', 'actor', 'bridal', 'wedding', 'model', 'building', 'charity', 'concrete']],
  mascara: [['mascara'], ['kabuki', 'clown'].concat(['eso', 'observatory', 'algeri', 'mohammedia', 'eglise', 'willaya', 'rue', 'montagne', 'telescope', 'asteroid', 'astronom', 'la silla', 'tamara', 'bibliot', 'mosque', 'church', 'market', 'oran'])],
  palette: [['eyeshadow', 'eye shadow', 'makeup palette', 'eye palette'], ['painter', 'painting', 'art', 'color wheel', 'artist']],
  'office-chair': [['office chair', 'desk chair', 'swivel chair', 'ergonomic chair', 'task chair', 'gaming chair', 'chair'], ['dentist', 'barber', 'wheelchair', 'electric chair', 'throne', 'church', 'garden', 'folding', 'deck', 'beach', 'museum', 'baroque', 'rococo', 'antique', 'historic', 'lawn', 'highchair', 'high chair', 'rocking', 'sedan', 'cathedra'].concat(PEOPLE)],
  bookshelf: [['bookshelf', 'bookcase', 'bookshelves', 'book shelf', 'shelving unit', 'shelf unit', 'book case'], ['library', 'museum']],
  'coffee-table': [['coffee table', 'center table', 'centre table', 'side table', 'living room table'], ['book']],
  desk: [['standing desk', 'sit-stand', 'writing desk', 'computer desk', 'office desk', 'workstation', 'desk'], ['help desk', 'front desk', 'reception', 'information desk', 'school', 'classroom', 'teacher', 'judge', 'news', 'anchor', 'president', 'senate', 'parliament', 'ministry', 'airport', 'check-in', 'hotel', 'bank', 'pawn', 'ticket', 'war', 'pilot', 'captain', 'museum', 'historic', 'resolute', 'service desk', 'registration'].concat(['rumsfeld', 'works at', 'president', 'secretary', 'dresser'])],
  'desk-lamp': [['desk lamp', 'table lamp', 'reading lamp', 'study lamp', 'led lamp'], ['museum', 'antique', 'tiffany'].concat(PEOPLE)],
  'floor-lamp': [['floor lamp', 'standing lamp', 'arc lamp', 'torchiere', 'standard lamp'], ['street', 'traffic', 'museum', 'antique'].concat(PEOPLE)],
  pendant: [['pendant light', 'pendant lamp', 'ceiling lamp', 'ceiling light', 'hanging lamp', 'chandelier'], ['museum', 'palace', 'cathedral', 'church', 'opera', 'castle', 'versailles', 'mosque'].concat(PEOPLE)],
  'duvet-set': [['duvet', 'bedding', 'comforter', 'bed linen', 'bedsheet', 'bed sheet', 'bedspread', 'quilt'], ['museum', 'hospital', 'refugee', 'patchwork exhibit', 'antique']],
  pillow: [['pillow'], ['fight', 'talk', 'neck', 'travel', 'museum', 'cat', 'dog', 'ceramic']],
  'weighted-blanket': [['weighted blanket', 'blanket', 'throw blanket'], ['emergency', 'space', 'refugee', 'relief', 'military', 'horse', 'saddle', 'baby', 'picnic', 'museum', 'indian', 'navajo', 'fire']],
  vase: [['vase'], ['greek', 'attic', 'amphora', 'etruscan', 'roman', 'ming', 'qing', 'dynasty', 'ancient', 'antique', 'museum', 'painting', 'red-figure', 'black-figure', 'sevres', 'portland', 'song'].concat(PEOPLE)],
  'wall-clock': [['wall clock', 'clock'], ['tower', 'big ben', 'town hall', 'cathedral', 'church', 'station', 'astronomical', 'sundial', 'cuckoo', 'grandfather', 'alarm', 'watch', 'museum', 'antique', 'historic', 'square', 'building', 'biological', 'body clock', 'time zone', 'atomic', 'doomsday', 'carillon', 'city'].concat(PEOPLE)],
  candle: [['candle'], ['vigil', 'church', 'cathedral', 'altar', 'procession', 'memorial', 'birthday', 'cake', 'menorah', 'diwali', 'funeral', 'prayer', 'shrine', 'temple', 'lantern', 'holy', 'mass', 'protest', 'candlelight'].concat(PEOPLE)],
  dumbbells: [['dumbbell', 'dumbell', 'kurzhantel'], []],
  'yoga-mat': [['yoga mat', 'exercise mat', 'fitness mat', 'gym mat'], []],
  bands: [['resistance band', 'exercise band', 'elastic band', 'theraband', 'loop band', 'fitness band'], ['rubber band ball']],
  'jump-rope': [['jump rope', 'skipping rope', 'jumping rope', 'skip rope'], []],
  tent: [['tent'], ['circus', 'refugee', 'military', 'festival', 'wedding', 'market', 'relief', 'emergency', 'army', 'event', 'marquee', 'beer', 'stall', 'vendor', 'fair', 'protest', 'camp site disaster', 'revival', 'mosque'].concat(['canal', 'frozen', 'homeless', 'encampment', 'squat', 'bristol', 'occupy', 'trin'])],
  'hiking-pack': [['hiking backpack', 'trekking backpack', 'hiking pack', 'rucksack', 'backpacker'], ['military', 'soldier', 'school', 'airport', 'trail', 'route', 'summit', 'peak', 'baby']],
  'water-bottle': [['water bottle', 'drinking bottle', 'thermos', 'flask', 'insulated bottle', 'reusable bottle', 'sports bottle'], ['mineral water', 'pollution', 'garbage', 'waste', 'recycl', 'litter', 'wine', 'beer', 'whisky', 'museum']],
  'sleeping-bag': [['sleeping bag', 'bivouac', 'bivy'], ['homeless', 'refugee', 'museum']],
  basketball: [['basketball'], GAME.concat(['arcade', 'dispenser', 'bay tek', 'alba', 'niners', 'bundesliga', 'gegen', 'berlin', 'final', 'cup', 'colección', 'deposit'])],
  'soccer-ball': [['soccer ball', 'football ball', 'association football ball', 'telstar', 'jabulani', 'brazuca', 'match ball'], GAME.concat(['gegen', 'bundesliga', 'laterne', 'hauptplatz', 'em-fu', 'alaska', 'iss-50', 'pokal', 'cup'])],
  volleyball: [['volleyball'], GAME.concat(['gegen', 'pokal', 'bundesliga', 'dvv', 'cup', 'final', 'dresdner', 'stairs'])],
  'coffee-beans': [['coffee bean', 'roasted coffee', 'coffee beans'], ['plantation', 'farm', 'harvest', 'picker', 'cherry', 'tree', 'plant']],
  'loose-tea': [['loose tea', 'tea leaves', 'loose leaf', 'dried tea', 'green tea', 'black tea', 'tea leaf'], ['plantation', 'field', 'bush', 'harvest', 'picker', 'garden', 'estate', 'ceremony', 'house', 'cup of tea', 'cup', 'processing', 'factory', 'picking'].concat(['shop', 'store', 'road', 'street', 'wellington', 'nathan', 'jordan', 'lin heung', 'factory'])],
  'cold-brew': [['cold brew', 'iced coffee', 'coffee bottle', 'cold coffee'], []],
  'olive-oil': [['olive oil', 'extra virgin', 'oil bottle'], ['tree', 'grove', 'harvest', 'press', 'mill', 'field', 'ancient', 'museum', 'lamp'].concat(['factory', 'pizza', 'vinegar', 'restaurant', 'bread', 'salad', 'shop', 'mill', 'pressing', 'production', 'water', 'lecithin'])],
  pasta: [['pasta', 'spaghetti', 'penne', 'fusilli', 'macaroni', 'tagliatelle', 'rigatoni', 'farfalle', 'linguine', 'noodle'], ['museum', 'machine', 'factory', 'monster'].concat(['sci', 'csiro', 'steak', 'science', 'chip', 'salad', 'restaurant', 'sauce', 'safeway', 'shelves'])],
  honey: [['honey jar', 'honey', 'honeycomb'], ['nga', 'pewter', 'gallery', 'sculpture', 'bee', 'bees', 'beehive', 'apiary', 'hive', 'wasp', 'bear', 'badger', 'honeymoon', 'honeydew', 'flower', 'honeysuckle', 'harvest'].concat(['stall', 'fair', 'show', 'market', 'guanshengyuan'])],
  granola: [['granola', 'muesli', 'cereal', 'oatmeal'], ['museum', 'factory', 'field', 'plantation']],
  apples: [['apple', 'apples'], ['apple inc', 'macbook', 'iphone', 'ipad', 'imac', 'store', 'logo', 'tree', 'blossom', 'orchard', 'pie', 'cake', 'juice', 'computer', 'watch', 'mac', 'steve', 'tv', 'pay', 'cider', 'vinegar', 'strudel', 'crumble', 'sauce', 'butter', 'cart', 'big apple', 'new york', 'snake', 'adam', 'eve', 'painting', 'museum', 'wassail', 'festival']],
  avocados: [['avocado'], ['tree', 'toast', 'salad', 'guacamole', 'sushi', 'flower', 'plant', 'seedling', 'oil', 'roll', 'orchard', 'farm']],
  tomatoes: [['tomato', 'tomatoes'], ['plant', 'plants', 'seedling', 'garden', 'greenhouse', 'sauce', 'soup', 'ketchup', 'paste', 'salad', 'field', 'harvest', 'blight', 'festival', 'tomatina', 'sandwich', 'pizza', 'farm', 'vine', 'cultivation', 'market stall', 'throwing'].concat(['canning', 'processing', 'company', 'factory', 'cannery', 'bucket'])],
  'analog-watch': [['wristwatch', 'wrist watch', 'analog watch', 'analogue watch', 'watch'], ['smart', 'apple', 'digital', 'pocket', 'stop', 'watchtower', 'neighborhood', 'tower', 'night', 'fire', 'bird', 'whale', 'security', 'guard', 'dog', 'museum', 'antique', 'vintage', 'broadway', 'bear']],
  'digital-watch': [['digital watch', 'casio', 'g-shock', 'lcd watch', 'sports watch', 'sport watch'], ['smartwatch', 'apple watch', 'museum']],
  necklace: [['necklace', 'pendant'], ANCIENT.concat(['traditional', 'king', 'queen', 'beads from', 'ceremony', 'costume'])],
  bracelet: [['bracelet', 'bangle'], ANCIENT.concat(['traditional', 'ceremony', 'costume', 'friendship bracelet maker'])],
  earrings: [['earring', 'ear ring'], ANCIENT.concat(['traditional', 'ceremony', 'costume', 'piercing'])],
  wallet: [['wallet'], ['hardware wallet', 'bitcoin', 'crypto', 'ledger', 'trezor', 'e-wallet', 'digital wallet', 'apple wallet', 'pay', 'paypal', 'museum', 'phone wallet app']],
  'card-holder': [['card holder', 'cardholder', 'card case', 'card wallet', 'business card holder', 'card sleeve'], ['credit card terminal']],
  belt: [['leather belt', 'belt buckle', 'belt'], ['coat', 'jacket', 'dress', 'lindbergh', 'given to', 'dpla', 'soviet', 'seat', 'conveyor', 'black belt', 'karate', 'judo', 'taekwondo', 'asteroid', 'green belt', 'rust', 'bible', 'kuiper', 'safety', 'tool', 'sam browne', 'military', 'garrison', 'chastity', 'championship', 'boxing', 'wrestling', 'fan belt', 'timing', 'drive belt', 'car', 'engine', 'machine', 'van allen', 'orion', 'cinch', 'corn', 'sun belt', 'earth', 'greenbelt', 'orogenic', 'volcanic', 'rain belt', 'wheat', 'cotton', 'snow', 'bible belt', 'museum']],
  suitcase: [['suitcase', 'luggage', 'carry-on', 'trolley bag', 'baggage', 'valise'], ['carousel', 'conveyor', 'abandoned', 'refugee', 'station', 'x-ray', 'lost', 'bomb', 'security', 'airport', 'museum', 'handling'].concat(['shop', 'store', 'dog', 'cat', 'market', 'vendor', 'novosibirsk', 'dubai'])],
  'packing-cubes': [['packing cube', 'packing cubes', 'packing organizer', 'travel organizer', 'compression bag', 'luggage organizer'], []],
  'travel-pillow': [['travel pillow', 'neck pillow', 'neck cushion', 'u-shaped pillow', 'airplane pillow'], []],
};

/* Commons categories that hold photographs OF each product type. Membership
 * of a category is far more reliable than a word in a file's title, so the
 * search runs inside these first (`incategory:"..."`).
 *   narrow: the category is specific enough that any usable photo in it counts
 *           (only the type's `not` words and the global reject list apply);
 *   broad:  the category mixes things (all necklaces, all tomatoes, every
 *           wristwatch), so the title must also name the product (PHOTO_TERMS).
 * A type with no entry here has no good category and is searched by title
 * alone, the least reliable path; the report flags those types. */
export const CATEGORIES = {
  earbuds: { cats: ['Wireless earbuds', 'Nothing ear (stick)', 'Google Pixel Buds', 'Here One'], narrow: true },
  headphones: { cats: ['Headphones'], narrow: false },
  speaker: { cats: ['Bluetooth speakers'], narrow: true },
  smartphone: { cats: ['Smartphones'], narrow: false },
  'phone-case': { cats: ['Mobile phone covers', 'Mobile phone accessories'], narrow: false },
  'wireless-charger': { cats: ['Qi (standard)', 'AirPower charger', 'Apple Magsafe wireless charger', 'Gigaset Wireless Fast Charger', 'Antyne Wireless Charger GY-68', 'USB-C wireless chargers'], narrow: true },
  laptop: { cats: ['Laptops'], narrow: true },
  keyboard: { cats: ['Computer keyboards'], narrow: true },
  monitor: { cats: ['Computer monitors'], narrow: true },
  mouse: { cats: ['Computer mice', 'Cordless computer mice', 'Corded computer mice'], narrow: true },
  'action-camera': { cats: ['GoPro', 'GoPro Hero4', 'GoPro Hero3', 'Gopro Hero5 Session'], narrow: true },
  mirrorless: { cats: ['Sony ILCE-6000', 'Canon EOS M50', 'Fujifilm X-T3', 'Canon EOS RP', 'Fujifilm X-T4', 'Fujifilm X-S10', 'Canon EOS R6', 'Panasonic Lumix DC-S5', 'Fujifilm X-Pro3', 'Fujifilm X-T30'], narrow: false },
  tripod: { cats: ['Tripods (photography)', 'Tripod heads'], narrow: true },
  'smart-tv': { cats: ['Smart TV'], narrow: true },
  soundbar: { cats: ['Soundbars'], narrow: true },
  projector: { cats: ['Video projectors', 'Laser projector'], narrow: true },
  smartwatch: { cats: ['Smartwatches', 'Google Pixel Watch', 'Sony SmartWatch'], narrow: true },
  'fitness-band': { cats: ['Microsoft Band', 'Microsoft Band 2', 'Xiaomi Mi Band', 'Smart bands', 'Activity trackers'], narrow: true },
  'smart-bulb': { cats: ['LED lamps'], narrow: false },
  'security-camera': { cats: ['Security cameras'], narrow: false },
  'smart-plug': { cats: ['Smart plugs', 'Wemo Mini Smart Plug', 'Verisure SmartPlug', 'TP-Link HS110'], narrow: true },
  tshirt: { cats: ['T-shirts'], narrow: false },
  hoodie: { cats: ['Hoodies'], narrow: false },
  'button-shirt': { cats: ['Dress shirts', 'Button-down shirts'], narrow: true },
  'summer-dress': { cats: ['Summer dresses', 'Sundresses'], narrow: true },
  'maxi-dress': { cats: ['Maxi dresses', 'Fit & flare maxi dress'], narrow: true },
  'wrap-dress': { cats: ['Wrap dresses'], narrow: true },
  'denim-jacket': { cats: ['Denim jackets', 'Blue denim jackets', 'Short denim jackets'], narrow: true },
  'puffer-jacket': { cats: ['Down jackets', 'Winter jackets'], narrow: true },
  'rain-jacket': { cats: ['Raincoats', 'Windbreakers (clothing)'], narrow: false },
  backpack: { cats: ['Backpacks'], narrow: true },
  tote: { cats: ['Tote bags'], narrow: true },
  crossbody: { cats: ['Crossbody bags', 'Shoulder bags'], narrow: true },
  sunglasses: { cats: ['Sunglasses'], narrow: true },
  'blue-light': { cats: ['Reading glasses', 'Spectacles', 'Eyeglass frames', 'Eyewear'], narrow: true },
  serum: { cats: ['Skin care products', 'Skin care', 'Cosmetics'], narrow: false },
  moisturizer: { cats: ['Skin care products', 'Skin care', 'Cosmetics'], narrow: false },
  sunscreen: { cats: ['Sunscreen'], narrow: true },
  cleanser: { cats: ['Skin care products', 'Skin care', 'Cosmetics'], narrow: false },
  lipstick: { cats: ['Lipstick'], narrow: true },
  foundation: { cats: ['Face powder', 'Foundation (cosmetics)', 'Cosmetics'], narrow: false },
  mascara: { cats: ['Mascara', 'Cosmetics'], narrow: false },
  palette: { cats: ['Eye shadow palettes'], narrow: true },
  'office-chair': { cats: ['Office chairs', 'Gaming chairs'], narrow: true },
  bookshelf: { cats: ['Bookcases'], narrow: true },
  'coffee-table': { cats: ['Coffee tables'], narrow: true },
  desk: { cats: ['Standing desks', 'Sit-stand desks', 'Office desks'], narrow: true },
  'desk-lamp': { cats: ['Desk lamps', 'Table lamps'], narrow: true },
  'floor-lamp': { cats: ['Floor lamps', 'Torchieres'], narrow: true },
  pendant: { cats: ['Pendant lights'], narrow: true },
  'duvet-set': { cats: ['Duvet covers', 'Duvets', 'Bed linen'], narrow: true },
  pillow: { cats: ['Pillows'], narrow: false },
  'weighted-blanket': { cats: ['Weighted blankets', 'Blankets'], narrow: false },
  vase: { cats: ['Vases'], narrow: false },
  'wall-clock': { cats: ['Wall clocks'], narrow: true },
  candle: { cats: ['Scented candles', 'Candles'], narrow: false },
  dumbbells: { cats: ['Dumbbells'], narrow: true },
  'yoga-mat': { cats: ['Yoga mats'], narrow: true },
  bands: { cats: ['Resistance bands'], narrow: true },
  'jump-rope': { cats: ['Jump ropes'], narrow: true },
  tent: { cats: ['Dome tents', 'Tents'], narrow: false },
  'hiking-pack': { cats: ['Hiking equipment', 'Backpacks'], narrow: false },
  'water-bottle': { cats: ['Water bottles'], narrow: false },
  'sleeping-bag': { cats: ['Sleeping bags', 'Camping equipment'], narrow: false },
  basketball: { cats: ['Basketballs'], narrow: true },
  'soccer-ball': { cats: ['Association football balls'], narrow: true },
  volleyball: { cats: ['Volleyballs'], narrow: true },
  'coffee-beans': { cats: ['Coffee beans'], narrow: true },
  'loose-tea': { cats: ['Tea leaves', 'Black tea', 'Green tea'], narrow: false },
  'cold-brew': { cats: ['Cold brew'], narrow: true },
  'olive-oil': { cats: ['Olive oil'], narrow: true },
  pasta: { cats: ['Pasta'], narrow: true },
  honey: { cats: ['Honey jars', 'Honey'], narrow: false },
  granola: { cats: ['Granola', 'Muesli'], narrow: true },
  apples: { cats: ['Red apples', 'Apples'], narrow: true },
  avocados: { cats: ['Avocado'], narrow: true },
  tomatoes: { cats: ['Tomatoes'], narrow: true },
  'analog-watch': { cats: ['Quartz wristwatches'], narrow: true },
  'digital-watch': { cats: ['Digital watches'], narrow: true },
  necklace: { cats: ['Necklaces'], narrow: false },
  bracelet: { cats: ['Bracelets', 'Bangles'], narrow: false },
  earrings: { cats: ['Earrings'], narrow: false },
  wallet: { cats: ['Leather wallets', 'Wallets'], narrow: true },
  'card-holder': { cats: ['Credit card holders'], narrow: true },
  belt: { cats: ['Leather belts'], narrow: true },
  suitcase: { cats: ['Trolley suitcases', 'Suitcases'], narrow: true },
  // packing-cubes: no category exists; searched by title.
  'travel-pillow': { cats: ['Neck pillows', 'Travel pillows'], narrow: true },
};
