/* The marketplace catalog's shape: how many products each category and
 * subcategory gets, and, per product type, everything the generator needs to
 * write believable data (spec fields, key features, variants, price band) and
 * everything the image step needs to find matching photos (search query and
 * the words a photo's description must / must not contain).
 *
 * Categories and subcategory ids are the app's own (public/js/data.js), so
 * generated products land in the existing browse pages. Counts sum to 1000.
 * Adding a product type is a data edit here, nothing else.
 */

const COLORS = ['Black', 'White', 'Silver', 'Navy', 'Forest Green', 'Sand', 'Rose', 'Charcoal'];
const SOFT_COLORS = ['Ivory', 'Sage', 'Dusty Blue', 'Terracotta', 'Charcoal', 'Oat'];
const APPAREL = ['XS', 'S', 'M', 'L', 'XL', 'XXL'];
const SHADES = ['Ivory', 'Beige', 'Honey', 'Caramel', 'Mocha'];

/* t(): one product type. `specs` are [label, options] pairs, a random option
 * is picked per product. `must` / `reject` match whole words in a photo's
 * description. `price` is the [min, max] band in dollars. */
const t = (key, noun, o) => ({ key, noun, reject: [], ...o });

export const TAXONOMY = {
  electronics: {
    audio: { count: 40, types: [
      t('earbuds', 'Wireless Earbuds', { q: 'wireless earbuds', must: ['earbud', 'earphone', 'headphone', 'airpod'], price: [19, 149],
        uses: ['commutes', 'workouts', 'long calls'], series: ['Pulse', 'Drift', 'Aero', 'Beat'],
        specs: [['Driver size', ['6 mm', '8 mm', '10 mm', '11 mm']], ['Battery life', ['6 h (24 h with case)', '8 h (32 h with case)', '10 h (40 h with case)']], ['Bluetooth', ['5.2', '5.3', '5.4']], ['Water resistance', ['IPX4', 'IPX5', 'IPX7']], ['Noise control', ['Active noise cancelling', 'Ambient mode', 'Passive isolation']]],
        features: ['Low-latency gaming mode', 'Wireless charging case', 'Touch controls on each bud', 'Dual-microphone call clarity', 'Multipoint pairing with two devices', 'Three sizes of silicone tips included', 'Find-my-earbuds app support'],
        variants: [['Color', COLORS.slice(0, 5)]] }),
      t('headphones', 'Over-Ear Headphones', { q: 'over ear headphones', must: ['headphone', 'headset'], price: [39, 299],
        uses: ['studio listening', 'flights', 'home offices'], series: ['Studio', 'Summit', 'Orbit', 'Halo'],
        specs: [['Driver size', ['40 mm', '45 mm', '50 mm']], ['Battery life', ['30 h', '40 h', '60 h']], ['Bluetooth', ['5.0', '5.2', '5.3']], ['Weight', ['240 g', '260 g', '285 g']], ['Noise control', ['Hybrid ANC', 'Adaptive ANC', 'Passive isolation']]],
        features: ['Memory-foam ear cushions', 'Foldable swivel design', 'Wired mode with a detachable cable', 'Fast charge: 10 minutes for 5 hours', 'Companion app with a 10-band equalizer', 'Hard travel case included'],
        variants: [['Color', COLORS.slice(0, 4)]] }),
      t('speaker', 'Portable Bluetooth Speaker', { q: 'bluetooth speaker', must: ['speaker'], price: [25, 220],
        uses: ['picnics', 'pool days', 'desk listening'], series: ['Boom', 'Echo', 'Wave', 'Cube'],
        specs: [['Output power', ['10 W', '20 W', '30 W', '40 W']], ['Battery life', ['12 h', '16 h', '20 h', '24 h']], ['Water resistance', ['IPX5', 'IPX6', 'IP67']], ['Bluetooth', ['5.0', '5.3']], ['Weight', ['420 g', '640 g', '980 g']]],
        features: ['Stereo pairing with a second speaker', 'Built-in power bank port', 'Floating, dustproof body', 'Detachable carry strap', 'Customizable light ring', 'Aux input for wired sources'],
        variants: [['Color', COLORS.slice(0, 5)]] }),
    ] },
    phones: { count: 40, types: [
      t('smartphone', 'Smartphone', { q: 'smartphone', must: ['smartphone', 'phone', 'iphone', 'mobile'], price: [149, 899],
        uses: ['photography', 'mobile gaming', 'everyday messaging'], series: ['Nova', 'Edge', 'Spark', 'Prime'],
        specs: [['Display', ['6.1" OLED, 90 Hz', '6.4" AMOLED, 120 Hz', '6.7" AMOLED, 120 Hz']], ['Chipset', ['8-core 4 nm', '8-core 5 nm', '8-core 6 nm']], ['RAM', ['6 GB', '8 GB', '12 GB']], ['Camera', ['50 MP main + 8 MP ultrawide', '64 MP main + 12 MP ultrawide', '108 MP main + 12 MP ultrawide']], ['Battery', ['4500 mAh', '5000 mAh', '5500 mAh']]],
        features: ['Fast charging up to 67 W', 'Dual SIM with 5G', 'In-display fingerprint sensor', 'Stereo speakers', 'Scratch-resistant glass', 'Three years of security updates'],
        variants: [['Storage', ['128GB', '256GB', '512GB']], ['Color', COLORS.slice(0, 4)]] }),
      t('phone-case', 'Protective Phone Case', { q: 'phone case', must: ['case', 'phone'], price: [9, 39],
        uses: ['daily carry', 'travel', 'active days'], series: ['Guard', 'Shell', 'Armor', 'Slim'],
        specs: [['Material', ['TPU and polycarbonate', 'Silicone', 'Recycled plastic']], ['Drop protection', ['Up to 2 m', 'Up to 3 m', 'Up to 4 m']], ['Wireless charging', ['Compatible']], ['Weight', ['32 g', '41 g', '56 g']]],
        features: ['Raised bezel protects screen and camera', 'Anti-yellowing finish', 'Soft-touch grip', 'Precise button cutouts', 'Works with wireless chargers'],
        variants: [['Color', COLORS.slice(0, 6)]] }),
      t('wireless-charger', 'Wireless Charging Pad', { q: 'wireless charger', must: ['charger', 'charging'], price: [12, 59],
        uses: ['nightstands', 'office desks', 'car-free commutes'], series: ['Flux', 'Pad', 'Dock', 'Glide'],
        specs: [['Output', ['10 W', '15 W', '20 W']], ['Input', ['USB-C', 'USB-C PD']], ['Standard', ['Qi', 'Qi2']], ['Cable length', ['1 m', '1.5 m']]],
        features: ['Foreign-object detection', 'Case-friendly up to 5 mm', 'Soft LED indicator', 'Non-slip surface', 'Over-temperature protection'],
        variants: [['Color', COLORS.slice(0, 3)]] }),
    ] },
    computing: { count: 45, types: [
      t('laptop', 'Laptop', { q: 'laptop computer', must: ['laptop', 'notebook', 'macbook'], price: [349, 1599],
        uses: ['study', 'remote work', 'creative projects'], series: ['Book', 'Air', 'Core', 'Slate'],
        specs: [['Display', ['14" IPS, 1920x1200', '15.6" IPS, 1920x1080', '16" IPS, 2560x1600']], ['Processor', ['8-core 3.2 GHz', '10-core 3.6 GHz', '12-core 4.2 GHz']], ['RAM', ['8 GB', '16 GB', '32 GB']], ['Battery', ['10 h', '14 h', '18 h']], ['Weight', ['1.25 kg', '1.45 kg', '1.8 kg']]],
        features: ['Backlit keyboard', 'Thunderbolt-class USB-C ports', 'Full HD webcam with privacy shutter', 'Fast-charge: 50% in 40 minutes', 'Aluminum body', 'Wi-Fi 6E'],
        variants: [['Storage', ['256GB', '512GB', '1TB']], ['Color', ['Silver', 'Space Grey', 'Midnight']]] }),
      t('keyboard', 'Mechanical Keyboard', { q: 'mechanical keyboard', must: ['keyboard'], price: [29, 189],
        uses: ['typing marathons', 'gaming', 'coding'], series: ['Type', 'Click', 'Forge', 'Key'],
        specs: [['Layout', ['Full-size', 'Tenkeyless', '75%', '65%']], ['Switches', ['Linear red', 'Tactile brown', 'Clicky blue']], ['Connection', ['Bluetooth + 2.4 GHz + USB-C', 'USB-C wired', 'Bluetooth + USB-C']], ['Keycaps', ['Double-shot PBT', 'ABS']], ['Battery', ['4000 mAh', '6000 mAh', 'Wired']]],
        features: ['Hot-swappable switches', 'Per-key RGB lighting', 'Gasket-mounted for a softer feel', 'Detachable USB-C cable', 'Pre-lubed stabilizers', 'Works with Mac and Windows'],
        variants: [['Color', ['Black', 'White', 'Grey', 'Mint']], ['Switch', ['Red', 'Brown', 'Blue']]] }),
      t('monitor', 'Monitor', { q: 'computer monitor', must: ['monitor', 'display', 'screen'], price: [99, 699],
        uses: ['spreadsheets', 'gaming', 'photo editing'], series: ['View', 'Vision', 'Pixel', 'Frame'],
        specs: [['Screen size', ['24"', '27"', '32"', '34" ultrawide']], ['Resolution', ['1920x1080', '2560x1440', '3840x2160']], ['Refresh rate', ['75 Hz', '144 Hz', '165 Hz']], ['Panel', ['IPS', 'VA']], ['Ports', ['HDMI 2.0 x2, DisplayPort 1.4', 'HDMI 2.1, DisplayPort 1.4, USB-C']]],
        features: ['Height-adjustable stand', 'Flicker-free backlight', 'Adaptive sync', 'Built-in blue-light filter', 'VESA mount ready', 'Factory color calibration'],
        variants: [['Size', ['24"', '27"', '32"']]] }),
      t('mouse', 'Wireless Mouse', { q: 'computer mouse', must: ['mouse'], price: [9, 99],
        uses: ['office work', 'travel', 'gaming'], series: ['Glide', 'Point', 'Swift', 'Click'],
        specs: [['Sensor', ['8000 DPI optical', '16000 DPI optical', '26000 DPI optical']], ['Battery life', ['60 days', '90 days', '120 days']], ['Buttons', ['6', '7', '8']], ['Weight', ['72 g', '85 g', '99 g']], ['Connection', ['2.4 GHz + Bluetooth', 'Bluetooth']]],
        features: ['Silent click switches', 'Ergonomic right-hand shape', 'Customizable side buttons', 'Quick-charge USB-C', 'Multi-device switching', 'Smooth PTFE feet'],
        variants: [['Color', COLORS.slice(0, 4)]] }),
    ] },
    cameras: { count: 30, types: [
      t('action-camera', '4K Action Camera', { q: 'action camera', must: ['camera', 'gopro'], price: [59, 399],
        uses: ['cycling', 'travel vlogs', 'water sports'], series: ['Trek', 'Pulse', 'Rush', 'Ridge'],
        specs: [['Video', ['4K 30 fps', '4K 60 fps', '5.3K 30 fps']], ['Stabilization', ['Electronic', '3-axis gimbal-style']], ['Waterproof', ['10 m', '12 m', '20 m with housing']], ['Battery', ['1250 mAh', '1700 mAh']], ['Screen', ['2" touch rear', '2.27" touch rear + front']]],
        features: ['Voice control', 'Time-lapse and slow motion', 'Removable batteries', 'Mounting kit included', 'Wi-Fi app transfer', 'Webcam mode'],
        variants: [['Bundle', ['Camera only', 'Accessory kit', 'Dual battery kit']]] }),
      t('mirrorless', 'Mirrorless Camera', { q: 'mirrorless camera', must: ['camera', 'mirrorless', 'dslr'], price: [499, 1799],
        uses: ['portraits', 'street photography', 'video work'], series: ['Lens', 'Frame', 'Optic', 'Capture'],
        specs: [['Sensor', ['24 MP APS-C', '26 MP APS-C', '33 MP full-frame']], ['Video', ['4K 30 fps', '4K 60 fps', '6K 30 fps']], ['Autofocus', ['425-point hybrid', '693-point hybrid', 'Subject-tracking AI']], ['Viewfinder', ['2.36M-dot OLED', '3.69M-dot OLED']], ['Weight', ['420 g', '520 g', '650 g']]],
        features: ['In-body image stabilization', 'Dual card slots', 'Tilting touchscreen', 'Weather-sealed body', 'Eye-detection autofocus', 'USB-C charging'],
        variants: [['Kit', ['Body only', 'With 18-55mm lens', 'With 24-70mm lens']]] }),
      t('tripod', 'Camera Tripod', { q: 'camera tripod', must: ['tripod'], price: [19, 189],
        uses: ['landscapes', 'long exposures', 'video calls'], series: ['Stand', 'Pod', 'Steady', 'Peak'],
        specs: [['Max height', ['140 cm', '160 cm', '180 cm']], ['Folded length', ['38 cm', '45 cm', '55 cm']], ['Load capacity', ['5 kg', '8 kg', '12 kg']], ['Material', ['Aluminum', 'Carbon fiber']], ['Weight', ['1.1 kg', '1.4 kg']]],
        features: ['Quick-release plate', 'Ball head with panning lock', 'Reversible center column', 'Non-slip rubber feet', 'Carry bag included'],
        variants: [['Color', ['Black', 'Graphite', 'Orange']]] }),
    ] },
    tv: { count: 30, types: [
      t('smart-tv', 'Smart TV', { q: 'smart tv living room', must: ['tv', 'television'], price: [229, 1499],
        uses: ['movie nights', 'sports', 'streaming'], series: ['Vista', 'Frame', 'Clear', 'Wide'],
        specs: [['Screen size', ['43"', '50"', '55"', '65"', '75"']], ['Resolution', ['4K UHD', '4K UHD']], ['Refresh rate', ['60 Hz', '120 Hz']], ['HDR', ['HDR10+', 'Dolby Vision']], ['HDMI ports', ['3', '4 (one HDMI 2.1)']]],
        features: ['Built-in streaming apps', 'Voice remote', 'Game mode with low input lag', 'Screen mirroring', 'Bezel-less design', 'Energy-saving mode'],
        variants: [['Size', ['43"', '50"', '55"', '65"']]] }),
      t('soundbar', 'Soundbar', { q: 'soundbar', must: ['soundbar', 'speaker', 'tv'], price: [59, 499],
        uses: ['dialogue clarity', 'movies', 'music'], series: ['Bar', 'Sonic', 'Cinema', 'Deep'],
        specs: [['Channels', ['2.1', '3.1', '5.1']], ['Output power', ['100 W', '200 W', '320 W']], ['Connections', ['HDMI ARC, optical, Bluetooth']], ['Subwoofer', ['Wireless', 'Built-in']]],
        features: ['Dialogue-boost mode', 'Wall-mount bracket included', 'Night mode', 'Works with the TV remote', 'Bluetooth music streaming'],
        variants: [['Color', ['Black', 'Charcoal']]] }),
      t('projector', 'Mini Projector', { q: 'home projector', must: ['projector'], price: [89, 599],
        uses: ['backyard movies', 'presentations', 'game nights'], series: ['Beam', 'Cine', 'Lumen', 'Glow'],
        specs: [['Resolution', ['1280x720 native', '1920x1080 native']], ['Brightness', ['400 ANSI lumens', '600 ANSI lumens', '900 ANSI lumens']], ['Image size', ['Up to 120"', 'Up to 150"']], ['Connectivity', ['HDMI, USB, Wi-Fi, Bluetooth']]],
        features: ['Auto keystone correction', 'Built-in speaker', 'Quiet cooling fan', 'Tripod-ready base', 'Screen mirroring from phones'],
        variants: [['Color', ['White', 'Black']]] }),
    ] },
    wearables: { count: 35, types: [
      t('smartwatch', 'Smartwatch', { q: 'smartwatch', must: ['smartwatch', 'watch'], price: [49, 399],
        uses: ['training', 'notifications', 'sleep tracking'], series: ['Fit', 'Time', 'Orbit', 'Pace'],
        specs: [['Display', ['1.4" AMOLED', '1.6" AMOLED', '1.9" AMOLED']], ['Battery life', ['5 days', '7 days', '14 days']], ['Water resistance', ['5 ATM', '10 ATM']], ['Sensors', ['Heart rate, SpO2, GPS', 'Heart rate, SpO2, GPS, temperature']], ['Case size', ['41 mm', '44 mm', '46 mm']]],
        features: ['Built-in GPS', '100+ workout modes', 'Sleep and stress tracking', 'Bluetooth calls', 'Always-on display', 'Interchangeable straps'],
        variants: [['Color', ['Black', 'Silver', 'Rose Gold', 'Navy']], ['Strap', ['Silicone', 'Leather', 'Metal mesh']]] }),
      t('fitness-band', 'Fitness Band', { q: 'fitness tracker band', must: ['fitness', 'tracker', 'band', 'watch'], price: [19, 99],
        uses: ['step goals', 'running', 'sleep'], series: ['Step', 'Beat', 'Lite', 'Move'],
        specs: [['Display', ['0.95" AMOLED', '1.1" AMOLED']], ['Battery life', ['14 days', '18 days', '21 days']], ['Water resistance', ['5 ATM']], ['Sensors', ['Heart rate, SpO2, accelerometer']], ['Weight', ['18 g', '24 g']]],
        features: ['Step, calorie and distance tracking', 'Guided breathing', 'Phone notifications', 'Magnetic fast charging', '30 sport modes'],
        variants: [['Color', ['Black', 'Blue', 'Pink', 'Green']]] }),
    ] },
    smarthome: { count: 30, types: [
      t('smart-bulb', 'Smart LED Bulb', { q: 'smart light bulb', must: ['bulb', 'light', 'lamp'], price: [8, 49],
        uses: ['movie lighting', 'wake-up routines', 'party scenes'], series: ['Glow', 'Hue', 'Spark', 'Beam'],
        specs: [['Brightness', ['800 lm', '1100 lm']], ['Color', ['16 million colors', 'Tunable white 2700-6500 K']], ['Base', ['E26', 'E27', 'GU10']], ['Connectivity', ['Wi-Fi 2.4 GHz', 'Zigbee']], ['Lifespan', ['25,000 h']]],
        features: ['Schedules and timers', 'Voice assistant compatible', 'Music sync mode', 'No hub required', 'Energy usage reports'],
        variants: [['Pack', ['1 bulb', '2 bulbs', '4 bulbs']]] }),
      t('security-camera', 'Indoor Security Camera', { q: 'security camera indoor', must: ['camera', 'security', 'cctv'], price: [25, 149],
        uses: ['watching pets', 'front-door checks', 'nursery monitoring'], series: ['Watch', 'Eye', 'Guard', 'View'],
        specs: [['Resolution', ['1080p', '2K', '4K']], ['Field of view', ['110°', '130°', '360° pan and tilt']], ['Night vision', ['Up to 10 m', 'Up to 12 m color']], ['Storage', ['microSD or cloud']], ['Audio', ['Two-way']]],
        features: ['Person and pet detection', 'Privacy mode with lens cover', 'Instant app alerts', 'Local storage option', 'Wall or shelf mounting'],
        variants: [['Color', ['White', 'Black']], ['Pack', ['1 camera', '2 cameras']]] }),
      t('smart-plug', 'Smart Plug', { q: 'smart plug outlet', must: ['plug', 'outlet', 'socket'], price: [7, 35],
        uses: ['lamps', 'coffee makers', 'holiday lights'], series: ['Plug', 'Switch', 'Link', 'Power'],
        specs: [['Max load', ['10 A', '15 A']], ['Connectivity', ['Wi-Fi 2.4 GHz']], ['Energy monitoring', ['Yes', 'No']], ['Size', ['Compact, does not block the second outlet']]],
        features: ['Schedules and countdown timers', 'Away mode that mimics presence', 'Voice assistant compatible', 'Overload protection', 'Simple app setup'],
        variants: [['Pack', ['1 plug', '2 plugs', '4 plugs']]] }),
    ] },
  },
  fashion: {
    tops: { count: 50, types: [
      t('tshirt', 'Cotton T-Shirt', { q: 't-shirt clothing', must: ['shirt', 't-shirt', 'tee'], price: [9, 39],
        uses: ['everyday wear', 'layering', 'weekend errands'], series: ['Basic', 'Tee', 'Core', 'Daily'],
        specs: [['Material', ['100% organic cotton', '100% cotton', '60% cotton, 40% polyester']], ['Fit', ['Regular', 'Relaxed', 'Slim']], ['Neckline', ['Crew neck', 'V-neck']], ['Care', ['Machine wash cold', 'Machine wash warm']], ['Origin', ['Portugal', 'Turkey', 'Vietnam']]],
        features: ['Pre-shrunk fabric', 'Tag-free neck label', 'Reinforced shoulder seams', 'Breathable midweight knit', 'Holds its shape after washing'],
        variants: [['Size', APPAREL], ['Color', COLORS.slice(0, 6)]] }),
      t('hoodie', 'Pullover Hoodie', { q: 'hoodie sweatshirt', must: ['hoodie', 'sweatshirt', 'sweater'], price: [25, 89],
        uses: ['cool evenings', 'travel days', 'gym warm-ups'], series: ['Cozy', 'Fleece', 'Loft', 'Camp'],
        specs: [['Material', ['80% cotton, 20% polyester', '100% organic cotton fleece']], ['Fit', ['Regular', 'Oversized']], ['Weight', ['320 gsm', '380 gsm', '420 gsm']], ['Care', ['Machine wash cold']], ['Origin', ['Portugal', 'Bangladesh']]],
        features: ['Brushed fleece lining', 'Kangaroo pocket', 'Adjustable drawcord hood', 'Ribbed cuffs and hem', 'Double-stitched seams'],
        variants: [['Size', APPAREL], ['Color', COLORS.slice(1, 7)]] }),
      t('button-shirt', 'Button-Up Shirt', { q: 'button up shirt', must: ['shirt', 'blouse'], price: [19, 79],
        uses: ['office days', 'dinners out', 'smart-casual weekends'], series: ['Oxford', 'Linen', 'Poplin', 'Studio'],
        specs: [['Material', ['100% cotton oxford', '100% linen', 'Cotton poplin']], ['Fit', ['Regular', 'Slim', 'Relaxed']], ['Collar', ['Button-down', 'Spread']], ['Care', ['Machine wash cold, iron medium']], ['Origin', ['India', 'Portugal']]],
        features: ['Wrinkle-resistant finish', 'Mother-of-pearl style buttons', 'Chest pocket', 'Curved hem for wearing out or tucked in', 'Breathable weave'],
        variants: [['Size', APPAREL], ['Color', ['White', 'Sky Blue', 'Sage', 'Navy', 'Stripe']]] }),
    ] },
    dresses: { count: 40, types: [
      t('summer-dress', 'Floral Summer Dress', { q: 'summer dress', must: ['dress'], price: [24, 89],
        uses: ['garden parties', 'beach holidays', 'brunch'], series: ['Bloom', 'Petal', 'Meadow', 'Sunny'],
        specs: [['Material', ['100% viscose', 'Cotton voile', 'Rayon crepe']], ['Length', ['Knee length', 'Midi']], ['Neckline', ['V-neck', 'Square neck']], ['Care', ['Hand wash cold', 'Machine wash gentle']], ['Origin', ['India', 'Vietnam']]],
        features: ['Lined bodice', 'Side pockets', 'Adjustable shoulder ties', 'Flowing, lightweight skirt', 'Hidden back zip'],
        variants: [['Size', APPAREL.slice(0, 5)], ['Print', ['Rose', 'Daisy', 'Lavender', 'Citrus']]] }),
      t('maxi-dress', 'Maxi Dress', { q: 'maxi dress', must: ['dress', 'gown'], price: [29, 119],
        uses: ['weddings as a guest', 'holidays', 'evening events'], series: ['Luna', 'Sol', 'Aria', 'Drape'],
        specs: [['Material', ['100% polyester georgette', 'Rayon blend', 'Satin crepe']], ['Length', ['Ankle length', 'Floor length']], ['Sleeves', ['Sleeveless', 'Short', 'Long']], ['Care', ['Machine wash gentle']], ['Origin', ['China', 'Turkey']]],
        features: ['Smocked elastic waist', 'Flattering A-line cut', 'Soft stretch fabric', 'Wrinkle-resistant', 'Easy care'],
        variants: [['Size', APPAREL.slice(0, 5)], ['Color', ['Emerald', 'Burgundy', 'Navy', 'Blush', 'Black']]] }),
      t('wrap-dress', 'Wrap Dress', { q: 'wrap dress', must: ['dress'], price: [34, 109],
        uses: ['work events', 'dinners', 'weekend trips'], series: ['Wrap', 'Tie', 'Grace', 'Muse'],
        specs: [['Material', ['Jersey knit', 'Crepe', 'Cotton blend']], ['Length', ['Knee length', 'Midi']], ['Sleeves', ['Three-quarter', 'Short']], ['Care', ['Machine wash cold']], ['Origin', ['Portugal', 'India']]],
        features: ['Adjustable tie waist', 'Stretch fabric that moves with you', 'Travel-friendly, packs flat', 'Secure wrap front', 'Fully lined skirt'],
        variants: [['Size', APPAREL.slice(0, 5)], ['Color', ['Black', 'Forest', 'Plum', 'Terracotta']]] }),
    ] },
    outerwear: { count: 40, types: [
      t('denim-jacket', 'Denim Jacket', { q: 'denim jacket', must: ['jacket', 'denim'], price: [39, 129],
        uses: ['spring layering', 'road trips', 'casual evenings'], series: ['Indigo', 'Ranch', 'Wash', 'Trucker'],
        specs: [['Material', ['100% cotton denim', '98% cotton, 2% elastane']], ['Fit', ['Regular', 'Cropped', 'Oversized']], ['Closure', ['Button front']], ['Care', ['Machine wash cold, inside out']], ['Origin', ['Turkey', 'Pakistan']]],
        features: ['Washed for a worn-in feel', 'Two chest and two hand pockets', 'Reinforced seams', 'Adjustable waist tabs', 'Gets softer with every wash'],
        variants: [['Size', APPAREL.slice(0, 5)], ['Wash', ['Light', 'Medium', 'Dark', 'Black']]] }),
      t('puffer-jacket', 'Puffer Jacket', { q: 'puffer jacket winter', must: ['jacket', 'coat', 'puffer'], price: [59, 219],
        uses: ['winter commutes', 'ski trips', 'cold walks'], series: ['Loft', 'Frost', 'Peak', 'Alpine'],
        specs: [['Fill', ['Recycled synthetic down', '700-fill duck down']], ['Shell', ['Water-repellent nylon', 'Ripstop polyester']], ['Temperature rating', ['Down to -5 °C', 'Down to -15 °C']], ['Care', ['Machine wash gentle, tumble dry low']], ['Origin', ['Vietnam', 'China']]],
        features: ['Water-repellent finish', 'Packable into its own pocket', 'Adjustable hood', 'Zippered hand pockets', 'Elastic cuffs seal out drafts'],
        variants: [['Size', APPAREL.slice(0, 5)], ['Color', ['Black', 'Olive', 'Navy', 'Cream']]] }),
      t('rain-jacket', 'Waterproof Rain Jacket', { q: 'rain jacket', must: ['jacket', 'raincoat', 'coat', 'rain'], price: [39, 169],
        uses: ['rainy commutes', 'trail hikes', 'festivals'], series: ['Storm', 'Shell', 'Drizzle', 'Trail'],
        specs: [['Waterproofing', ['10,000 mm', '15,000 mm', '20,000 mm']], ['Breathability', ['10,000 g/m²', '15,000 g/m²']], ['Seams', ['Fully taped']], ['Care', ['Machine wash cold, tumble dry low']], ['Origin', ['Vietnam', 'Indonesia']]],
        features: ['Fully taped seams', 'Stowable hood with a brim', 'Pit zips for ventilation', 'Packs into its own pocket', 'Reflective details'],
        variants: [['Size', APPAREL.slice(0, 5)], ['Color', ['Yellow', 'Navy', 'Forest', 'Black']]] }),
    ] },
    bags: { count: 40, types: [
      t('backpack', 'Everyday Backpack', { q: 'backpack', must: ['backpack', 'rucksack'], price: [24, 129],
        uses: ['campus days', 'commuting', 'weekend trips'], series: ['Pack', 'Daily', 'Roam', 'Metro'],
        specs: [['Capacity', ['18 L', '22 L', '28 L']], ['Material', ['Recycled polyester', 'Waxed canvas', 'Ripstop nylon']], ['Laptop sleeve', ['Fits up to 14"', 'Fits up to 16"']], ['Weight', ['0.6 kg', '0.8 kg', '1.0 kg']], ['Water resistance', ['Water-repellent']]],
        features: ['Padded laptop compartment', 'Hidden anti-theft pocket', 'Breathable back panel', 'Side bottle pockets', 'USB pass-through port', 'Luggage strap for suitcases'],
        variants: [['Color', COLORS.slice(0, 5)]] }),
      t('tote', 'Canvas Tote Bag', { q: 'tote bag', must: ['tote', 'bag'], price: [12, 69],
        uses: ['market runs', 'beach days', 'daily errands'], series: ['Tote', 'Carry', 'Market', 'Loop'],
        specs: [['Capacity', ['15 L', '20 L', '25 L']], ['Material', ['Heavy cotton canvas', 'Recycled canvas', 'Leather trim canvas']], ['Closure', ['Open top', 'Zip top']], ['Handle drop', ['25 cm', '30 cm']]],
        features: ['Inside zip pocket', 'Reinforced stitched handles', 'Holds up to 10 kg', 'Washable', 'Folds flat for storage'],
        variants: [['Color', ['Natural', 'Black', 'Olive', 'Navy']]] }),
      t('crossbody', 'Crossbody Bag', { q: 'crossbody bag', must: ['bag', 'handbag', 'purse'], price: [19, 109],
        uses: ['city walks', 'festivals', 'travel days'], series: ['Sling', 'Cross', 'Mini', 'Nook'],
        specs: [['Dimensions', ['22 x 15 x 7 cm', '25 x 17 x 8 cm']], ['Material', ['Vegan leather', 'Nylon', 'Pebbled faux leather']], ['Strap', ['Adjustable, 60-120 cm']], ['Closure', ['Zip', 'Magnetic flap']], ['Compartments', ['2', '3']]],
        features: ['Adjustable, removable strap', 'Interior card slots', 'Lightweight at under 400 g', 'Wipe-clean lining', 'Fits a phone and small wallet'],
        variants: [['Color', ['Black', 'Tan', 'Cream', 'Burgundy', 'Olive']]] }),
    ] },
    eyewear: { count: 30, types: [
      t('sunglasses', 'Polarized Sunglasses', { q: 'sunglasses', must: ['sunglass', 'glasses', 'eyewear'], price: [14, 109],
        uses: ['driving', 'beach days', 'city walks'], series: ['Shade', 'Ray', 'Coast', 'Solar'],
        specs: [['Lens', ['Polarized', 'Polarized, mirrored']], ['UV protection', ['UV400']], ['Frame', ['Acetate', 'Metal', 'Recycled plastic']], ['Lens width', ['52 mm', '54 mm', '58 mm']], ['Weight', ['24 g', '28 g', '32 g']]],
        features: ['100% UV400 protection', 'Scratch-resistant coating', 'Flexible hinges', 'Hard case and cloth included', 'Anti-glare lenses'],
        variants: [['Frame', ['Black', 'Tortoise', 'Gold', 'Clear']]] }),
      t('blue-light', 'Blue-Light Glasses', { q: 'computer glasses', must: ['glasses', 'eyeglasses', 'eyewear'], price: [12, 59],
        uses: ['long screen days', 'late-night reading', 'gaming'], series: ['Screen', 'Focus', 'Clear', 'Lens'],
        specs: [['Lens', ['Blue-light filtering', 'Blue-light filtering, anti-reflective']], ['Frame', ['TR90 plastic', 'Acetate', 'Metal']], ['Lens width', ['50 mm', '52 mm']], ['Weight', ['16 g', '20 g']]],
        features: ['Reduces screen glare', 'Spring hinges', 'Lightweight frame', 'Soft nose pads', 'Microfiber pouch included'],
        variants: [['Frame', ['Black', 'Tortoise', 'Crystal', 'Navy']]] }),
    ] },
  },
  beauty: {
    skincare: { count: 70, types: [
      t('serum', 'Face Serum', { q: 'face serum bottle', must: ['serum', 'bottle', 'skincare', 'dropper'], price: [9, 69],
        uses: ['morning routines', 'dull skin', 'evening care'], series: ['Glow', 'Dew', 'Pure', 'Renew'],
        specs: [['Key ingredient', ['2% hyaluronic acid', '10% vitamin C', '5% niacinamide', '0.3% retinol']], ['Volume', ['30 ml', '50 ml']], ['Skin type', ['All skin types', 'Normal to dry', 'Oily and combination']], ['Texture', ['Lightweight gel', 'Silky fluid']], ['Free from', ['Fragrance and parabens', 'Parabens and sulfates']]],
        features: ['Dermatologist tested', 'Absorbs in seconds', 'Vegan and cruelty free', 'Fragrance free', 'Airless pump keeps it fresh'],
        variants: [['Size', ['30 ml', '50 ml']]] }),
      t('moisturizer', 'Daily Moisturizer', { q: 'face cream moisturizer', must: ['cream', 'moisturizer', 'moisturiser', 'skincare', 'jar'], price: [8, 59],
        uses: ['dry weather', 'daily hydration', 'sensitive skin'], series: ['Soft', 'Dew', 'Calm', 'Cloud'],
        specs: [['Key ingredient', ['Ceramides', 'Shea butter', 'Squalane', 'Aloe vera']], ['Volume', ['50 ml', '75 ml']], ['Skin type', ['Dry', 'Sensitive', 'All skin types']], ['Texture', ['Rich cream', 'Light lotion']], ['Free from', ['Fragrance', 'Parabens']]],
        features: ['24-hour hydration', 'Non-greasy finish', 'Dermatologist tested', 'Recyclable jar', 'Suitable for sensitive skin'],
        variants: [['Size', ['50 ml', '75 ml']]] }),
      t('sunscreen', 'Daily Sunscreen', { q: 'sunscreen', must: ['sunscreen', 'sunblock', 'sun', 'lotion'], price: [8, 39],
        uses: ['daily commutes', 'beach days', 'outdoor sport'], series: ['Shield', 'Ray', 'Shade', 'Sun'],
        specs: [['SPF', ['SPF 30', 'SPF 50', 'SPF 50+']], ['Protection', ['Broad spectrum UVA/UVB']], ['Volume', ['50 ml', '100 ml']], ['Finish', ['No white cast', 'Matte', 'Dewy']], ['Water resistance', ['Up to 80 minutes']]],
        features: ['Reef-friendly formula', 'No white cast', 'Sits well under makeup', 'Fragrance free', 'Non-sticky texture'],
        variants: [['SPF', ['SPF 30', 'SPF 50']], ['Size', ['50 ml', '100 ml']]] }),
      t('cleanser', 'Gentle Facial Cleanser', { q: 'facial cleanser', must: ['cleanser', 'cleansing', 'skincare', 'face wash'], price: [6, 35],
        uses: ['morning washes', 'removing makeup', 'sensitive skin'], series: ['Fresh', 'Pure', 'Foam', 'Clear'],
        specs: [['Type', ['Gel cleanser', 'Cream cleanser', 'Foaming cleanser']], ['Volume', ['150 ml', '200 ml']], ['Skin type', ['All skin types', 'Oily', 'Sensitive']], ['pH', ['5.5']], ['Free from', ['Sulfates', 'Fragrance and sulfates']]],
        features: ['Soap-free formula', 'Removes sunscreen and light makeup', 'Leaves skin soft, not tight', 'pH balanced', 'Vegan formula'],
        variants: [['Size', ['150 ml', '200 ml']]] }),
    ] },
    makeup: { count: 50, types: [
      t('lipstick', 'Satin Lipstick', { q: 'lipstick', must: ['lipstick', 'lip'], price: [6, 39],
        uses: ['all-day wear', 'events', 'quick touch-ups'], series: ['Velvet', 'Tint', 'Bold', 'Satin'],
        specs: [['Finish', ['Satin', 'Matte', 'Cream']], ['Weight', ['3.5 g', '4 g']], ['Wear time', ['Up to 8 hours', 'Up to 10 hours']], ['Free from', ['Parabens', 'Parabens and fragrance']]],
        features: ['Comfortable, non-drying formula', 'Highly pigmented', 'Vitamin E enriched', 'Vegan and cruelty free', 'Transfer-resistant'],
        variants: [['Shade', ['Rosewood', 'Berry', 'Coral', 'Soft Beige', 'Brick']]] }),
      t('foundation', 'Skin-Tint Foundation', { q: 'foundation makeup', must: ['foundation', 'makeup', 'cosmetic'], price: [9, 49],
        uses: ['daily wear', 'events', 'photos'], series: ['Skin', 'Veil', 'Base', 'Natural'],
        specs: [['Coverage', ['Light to medium', 'Medium to full']], ['Finish', ['Natural', 'Matte', 'Radiant']], ['Volume', ['30 ml']], ['SPF', ['SPF 15', 'No SPF']], ['Shade range', ['24 shades', '30 shades']]],
        features: ['Buildable coverage', 'Lightweight, breathable feel', 'Pump bottle', 'Oil-free', 'Does not settle into lines'],
        variants: [['Shade', SHADES]] }),
      t('mascara', 'Volumizing Mascara', { q: 'mascara', must: ['mascara', 'eyelash', 'lashes', 'makeup'], price: [5, 29],
        uses: ['everyday looks', 'long days', 'events'], series: ['Lash', 'Lift', 'Volume', 'Curl'],
        specs: [['Effect', ['Volume', 'Length and curl', 'Lengthening']], ['Formula', ['Waterproof', 'Smudge-proof', 'Water-based']], ['Brush', ['Curved silicone', 'Classic fiber']], ['Weight', ['9 ml', '10 ml']]],
        features: ['No clumps or flakes', 'Ophthalmologist tested', 'Removes with warm water or cleanser', 'Vegan formula', 'Holds a curl all day'],
        variants: [['Shade', ['Black', 'Brown black']]] }),
      t('palette', 'Eyeshadow Palette', { q: 'eyeshadow palette', must: ['palette', 'eyeshadow', 'makeup', 'eye shadow'], price: [9, 49],
        uses: ['day-to-night looks', 'travel', 'creative looks'], series: ['Dusk', 'Tone', 'Muse', 'Shade'],
        specs: [['Shades', ['9', '12', '18']], ['Finish', ['Matte and shimmer', 'Matte', 'Shimmer']], ['Weight', ['10 g', '14 g']], ['Case', ['Mirrored compact']]],
        features: ['Blendable, highly pigmented shades', 'Mirror included', 'Crease-resistant', 'Talc-free', 'Neutral and bold shades together'],
        variants: [['Palette', ['Warm Neutrals', 'Cool Tones', 'Earth Tones']]] }),
    ] },
  },
  home: {
    furniture: { count: 45, types: [
      t('office-chair', 'Ergonomic Office Chair', { q: 'office chair', must: ['chair'], price: [89, 449],
        uses: ['long workdays', 'home offices', 'study sessions'], series: ['Desk', 'Task', 'Posture', 'Flex'],
        specs: [['Material', ['Breathable mesh', 'Mesh and fabric']], ['Weight capacity', ['120 kg', '136 kg']], ['Seat height', ['44-54 cm', '45-55 cm']], ['Armrests', ['3D adjustable', '2D adjustable']], ['Recline', ['Up to 135°', 'Up to 120°']]],
        features: ['Adjustable lumbar support', 'Breathable mesh back', 'Smooth-rolling casters', 'Tilt lock', 'Easy assembly in 15 minutes'],
        variants: [['Color', ['Black', 'Grey', 'White']]] }),
      t('bookshelf', 'Bookshelf', { q: 'bookshelf', must: ['bookshelf', 'shelf', 'shelves', 'bookcase'], price: [49, 299],
        uses: ['living rooms', 'home offices', 'kids rooms'], series: ['Shelf', 'Stack', 'Frame', 'Ladder'],
        specs: [['Dimensions', ['80 x 24 x 180 cm', '60 x 30 x 150 cm', '100 x 30 x 120 cm']], ['Material', ['Engineered wood', 'Solid pine', 'Metal and wood']], ['Shelves', ['4', '5', '6']], ['Load per shelf', ['15 kg', '25 kg']], ['Assembly', ['Required, tools included']]],
        features: ['Adjustable shelf heights', 'Wall anchor included', 'Scratch-resistant surface', 'Open back for cable routing', 'Easy-clean finish'],
        variants: [['Finish', ['Oak', 'Walnut', 'White', 'Black']]] }),
      t('coffee-table', 'Coffee Table', { q: 'coffee table living room', must: ['table', 'coffee table'], price: [59, 349],
        uses: ['living rooms', 'small apartments', 'movie nights'], series: ['Low', 'Round', 'Nest', 'Loft'],
        specs: [['Dimensions', ['90 x 50 x 40 cm', '100 x 60 x 45 cm', '80 cm round x 42 cm']], ['Material', ['Solid oak', 'Engineered wood', 'Tempered glass and steel']], ['Weight capacity', ['30 kg', '45 kg']], ['Storage', ['Lower shelf', 'None']]],
        features: ['Rounded safe corners', 'Water-resistant top', 'Lower storage shelf', 'Stable wide stance', 'Simple tool-free legs'],
        variants: [['Finish', ['Oak', 'Walnut', 'Black', 'White']]] }),
      t('desk', 'Standing Desk', { q: 'desk workspace', must: ['desk', 'table', 'workspace'], price: [149, 599],
        uses: ['home offices', 'study', 'creative work'], series: ['Rise', 'Stand', 'Work', 'Lift'],
        specs: [['Desktop size', ['120 x 60 cm', '140 x 70 cm', '160 x 75 cm']], ['Height range', ['72-120 cm', '70-125 cm']], ['Motor', ['Single', 'Dual']], ['Weight capacity', ['80 kg', '100 kg']], ['Memory presets', ['3', '4']]],
        features: ['Quiet electric motor', 'Anti-collision sensor', 'Cable management tray', 'Memory height presets', 'Sturdy steel frame'],
        variants: [['Top', ['Oak', 'Walnut', 'White', 'Black']], ['Width', ['120 cm', '140 cm', '160 cm']]] }),
    ] },
    lighting: { count: 35, types: [
      t('desk-lamp', 'LED Desk Lamp', { q: 'desk lamp', must: ['lamp', 'desk lamp', 'light'], price: [14, 89],
        uses: ['late-night study', 'drawing', 'reading'], series: ['Task', 'Study', 'Glow', 'Arc'],
        specs: [['Brightness', ['500 lm', '800 lm']], ['Color temperature', ['2700-6500 K']], ['Power', ['9 W', '12 W']], ['Control', ['Touch dimmer', 'Rotary dial']], ['Extras', ['USB charging port', 'Wireless charging base']]],
        features: ['Five brightness levels', 'Flicker-free light', 'Flexible gooseneck', 'Memory function', 'Auto-off timer'],
        variants: [['Color', ['White', 'Black', 'Wood']]] }),
      t('floor-lamp', 'Floor Lamp', { q: 'floor lamp', must: ['lamp', 'floor lamp', 'light'], price: [39, 219],
        uses: ['reading corners', 'living rooms', 'bedrooms'], series: ['Arc', 'Tall', 'Tripod', 'Glow'],
        specs: [['Height', ['150 cm', '165 cm', '180 cm']], ['Base', ['Weighted steel', 'Wood tripod']], ['Bulb', ['E26/E27, up to 60 W', 'LED included']], ['Switch', ['Foot switch', 'Inline switch']], ['Shade', ['Linen', 'Metal']]],
        features: ['Dimmable with a compatible bulb', 'Stable weighted base', 'Adjustable head', 'Easy assembly', 'Warm ambient glow'],
        variants: [['Finish', ['Black', 'Brass', 'White', 'Walnut']]] }),
      t('pendant', 'Pendant Light', { q: 'pendant light', must: ['pendant', 'light', 'lamp', 'chandelier'], price: [29, 199],
        uses: ['dining tables', 'kitchen islands', 'hallways'], series: ['Drop', 'Dome', 'Globe', 'Cone'],
        specs: [['Diameter', ['30 cm', '40 cm', '50 cm']], ['Material', ['Metal', 'Rattan', 'Glass']], ['Bulb', ['E26/E27, up to 60 W']], ['Cord length', ['120 cm adjustable']], ['Mounting', ['Ceiling hook or canopy']]],
        features: ['Adjustable hanging height', 'Works with smart bulbs', 'Easy hardwire install', 'Warm diffused glow', 'Mounting hardware included'],
        variants: [['Finish', ['Black', 'Brass', 'White', 'Natural']]] }),
    ] },
    bedding: { count: 35, types: [
      t('duvet-set', 'Duvet Cover Set', { q: 'bedding duvet', must: ['bed', 'bedding', 'duvet', 'bedroom', 'linen', 'sheet'], price: [29, 159],
        uses: ['bedrooms', 'guest rooms', 'cooler nights'], series: ['Linen', 'Rest', 'Cloud', 'Weave'],
        specs: [['Material', ['100% cotton percale', 'Washed linen', 'Brushed microfiber']], ['Thread count', ['200', '300', '400']], ['Includes', ['Duvet cover and 2 pillow shams']], ['Care', ['Machine wash warm']], ['Closure', ['Hidden button', 'Zipper']]],
        features: ['Gets softer with washing', 'Corner ties keep the duvet in place', 'Hypoallergenic', 'Breathable in summer', 'OEKO-TEX certified fabric'],
        variants: [['Size', ['Twin', 'Queen', 'King']], ['Color', SOFT_COLORS.slice(0, 5)]] }),
      t('pillow', 'Memory Foam Pillow', { q: 'pillow bed', must: ['pillow', 'bed', 'bedroom'], price: [14, 79],
        uses: ['side sleepers', 'back sleepers', 'neck support'], series: ['Rest', 'Cloud', 'Nest', 'Dream'],
        specs: [['Fill', ['Shredded memory foam', 'Gel-infused memory foam', 'Down alternative']], ['Size', ['Standard', 'Queen', 'King']], ['Height', ['10 cm', '12 cm', '14 cm']], ['Cover', ['Bamboo blend', 'Cotton']], ['Care', ['Cover machine washable']]],
        features: ['Adjustable fill height', 'Breathable cover', 'Keeps shape night after night', 'Hypoallergenic fill', 'Cooling gel layer'],
        variants: [['Size', ['Standard', 'Queen', 'King']]] }),
      t('weighted-blanket', 'Weighted Blanket', { q: 'blanket bed', must: ['blanket', 'throw', 'bed'], price: [39, 169],
        uses: ['restful nights', 'couch evenings', 'cold rooms'], series: ['Hug', 'Calm', 'Cozy', 'Drift'],
        specs: [['Weight', ['5 kg', '7 kg', '9 kg']], ['Size', ['120 x 180 cm', '150 x 200 cm']], ['Fill', ['Glass beads']], ['Cover', ['Cotton', 'Bamboo']], ['Care', ['Machine wash cold']]],
        features: ['Evenly distributed weight in stitched squares', 'Breathable cover', 'Removable duvet cover option', 'Quiet fill', 'Machine washable'],
        variants: [['Weight', ['5 kg', '7 kg', '9 kg']], ['Color', ['Grey', 'Navy', 'Oat']]] }),
    ] },
    decor: { count: 35, types: [
      t('vase', 'Ceramic Vase', { q: 'ceramic vase', must: ['vase', 'ceramic', 'flowers'], price: [12, 79],
        uses: ['shelves', 'dining tables', 'entryways'], series: ['Form', 'Clay', 'Curve', 'Arch'],
        specs: [['Height', ['18 cm', '24 cm', '30 cm']], ['Material', ['Glazed ceramic', 'Stoneware', 'Terracotta']], ['Finish', ['Matte', 'Glossy', 'Speckled']], ['Waterproof', ['Yes, sealed inside']]],
        features: ['Handmade-style glaze variations', 'Works with fresh or dried flowers', 'Wide stable base', 'Sealed interior', 'Felt pad protects surfaces'],
        variants: [['Color', SOFT_COLORS.slice(0, 5)]] }),
      t('wall-clock', 'Wall Clock', { q: 'wall clock', must: ['clock'], price: [14, 89],
        uses: ['living rooms', 'kitchens', 'offices'], series: ['Tick', 'Hour', 'Round', 'Line'],
        specs: [['Diameter', ['30 cm', '40 cm', '50 cm']], ['Movement', ['Silent quartz']], ['Material', ['Wood', 'Metal', 'Glass']], ['Power', ['1 AA battery (not included)']]],
        features: ['Silent sweep movement', 'Easy-read numerals', 'Lightweight hanging hook', 'Clean modern look', 'Battery lasts about a year'],
        variants: [['Color', ['Black', 'White', 'Walnut', 'Brass']]] }),
      t('candle', 'Scented Soy Candle', { q: 'scented candle', must: ['candle'], price: [8, 45],
        uses: ['evening relaxing', 'bath time', 'gifts'], series: ['Glow', 'Wick', 'Amber', 'Calm'],
        specs: [['Wax', ['100% soy wax', 'Soy and coconut wax']], ['Burn time', ['40 hours', '55 hours', '70 hours']], ['Weight', ['200 g', '300 g']], ['Wick', ['Cotton']], ['Vessel', ['Reusable glass jar']]],
        features: ['Clean-burning soy wax', 'Cotton wick', 'Reusable glass jar', 'Phthalate-free fragrance', 'Hand-poured in small batches'],
        variants: [['Scent', ['Cedar and Amber', 'Fresh Linen', 'Vanilla Bean', 'Sea Salt', 'Fig']]] }),
    ] },
  },
  sports: {
    fitness: { count: 40, types: [
      t('dumbbells', 'Adjustable Dumbbell Set', { q: 'dumbbells', must: ['dumbbell', 'weights', 'weight'], price: [29, 349],
        uses: ['home workouts', 'strength training', 'small spaces'], series: ['Iron', 'Lift', 'Force', 'Core'],
        specs: [['Weight range', ['2-12 kg', '2-24 kg', '5-32 kg']], ['Adjustment', ['Dial', 'Pin-select']], ['Material', ['Steel and rubber', 'Cast iron']], ['Handle', ['Knurled steel']], ['Includes', ['Storage tray']]],
        features: ['Replaces a full rack of dumbbells', 'Quiet, rubber-coated plates', 'Secure locking mechanism', 'Knurled grip', 'Space-saving tray'],
        variants: [['Weight', ['12 kg', '24 kg', '32 kg']]] }),
      t('yoga-mat', 'Non-Slip Yoga Mat', { q: 'yoga mat', must: ['yoga', 'mat'], price: [14, 89],
        uses: ['yoga practice', 'stretching', 'floor workouts'], series: ['Flow', 'Grip', 'Zen', 'Stretch'],
        specs: [['Thickness', ['4 mm', '6 mm', '8 mm']], ['Size', ['173 x 61 cm', '183 x 66 cm']], ['Material', ['TPE', 'Natural rubber', 'Cork and TPE']], ['Weight', ['900 g', '1.2 kg']]],
        features: ['Non-slip on both sides', 'Moisture-resistant surface', 'Carry strap included', 'Alignment guide lines', 'Odor-free material'],
        variants: [['Color', ['Purple', 'Teal', 'Grey', 'Black', 'Coral']]] }),
      t('bands', 'Resistance Band Set', { q: 'resistance bands', must: ['band', 'resistance', 'exercise', 'workout'], price: [9, 49],
        uses: ['mobility work', 'travel workouts', 'physical therapy'], series: ['Stretch', 'Pull', 'Loop', 'Flex'],
        specs: [['Bands in set', ['3', '5']], ['Resistance range', ['5-40 lb', '10-50 lb', '10-150 lb']], ['Material', ['Natural latex', 'Fabric-covered latex']], ['Includes', ['Carry bag, exercise guide']]],
        features: ['Color-coded resistance levels', 'Snap-resistant layered latex', 'Door anchor and handles in the kit', 'Fits in a carry bag', 'Printed exercise guide'],
        variants: [['Set', ['Light', 'Medium', 'Heavy']]] }),
      t('jump-rope', 'Speed Jump Rope', { q: 'jump rope', must: ['rope', 'jump', 'skipping'], price: [6, 35],
        uses: ['cardio', 'warm-ups', 'boxing training'], series: ['Skip', 'Speed', 'Hop', 'Cord'],
        specs: [['Length', ['Adjustable up to 3 m']], ['Cable', ['Coated steel', 'PVC']], ['Handles', ['Aluminum', 'Foam grip']], ['Bearings', ['Ball bearing swivel']]],
        features: ['Tangle-free swivel', 'Adjustable length', 'Replaceable cable', 'Comfortable non-slip handles', 'Pouch included'],
        variants: [['Color', ['Black', 'Blue', 'Red', 'Green']]] }),
    ] },
    outdoor: { count: 35, types: [
      t('tent', 'Backpacking Tent', { q: 'camping tent', must: ['tent', 'camping'], price: [69, 399],
        uses: ['weekend camping', 'trail trips', 'festivals'], series: ['Camp', 'Trail', 'Ridge', 'Nest'],
        specs: [['Capacity', ['2 person', '3 person', '4 person']], ['Packed weight', ['1.8 kg', '2.4 kg', '3.2 kg']], ['Waterproofing', ['3000 mm', '5000 mm']], ['Season', ['3-season']], ['Poles', ['Aluminum']]],
        features: ['Pitches in under five minutes', 'Taped seams', 'Two doors and two vestibules', 'Mesh inner for airflow', 'Includes stakes and repair kit'],
        variants: [['Capacity', ['2 person', '3 person', '4 person']], ['Color', ['Green', 'Orange', 'Grey']]] }),
      t('hiking-pack', 'Hiking Backpack', { q: 'hiking backpack', must: ['backpack', 'hiking', 'rucksack'], price: [39, 249],
        uses: ['day hikes', 'weekend treks', 'travel'], series: ['Trek', 'Summit', 'Ridge', 'Trail'],
        specs: [['Capacity', ['30 L', '40 L', '55 L']], ['Material', ['Ripstop nylon']], ['Back system', ['Ventilated mesh', 'Adjustable torso']], ['Weight', ['1.0 kg', '1.4 kg', '1.9 kg']], ['Rain cover', ['Included']]],
        features: ['Hydration reservoir compatible', 'Padded hip belt with pockets', 'Integrated rain cover', 'Trekking pole loops', 'Adjustable torso length'],
        variants: [['Size', ['30 L', '40 L', '55 L']], ['Color', ['Green', 'Black', 'Blue', 'Orange']]] }),
      t('water-bottle', 'Insulated Water Bottle', { q: 'water bottle', must: ['bottle', 'flask', 'tumbler'], price: [9, 49],
        uses: ['hot days', 'commutes', 'trailheads'], series: ['Flask', 'Chill', 'Sip', 'Drift'],
        specs: [['Capacity', ['500 ml', '750 ml', '1 L']], ['Material', ['18/8 stainless steel']], ['Insulation', ['Cold 24 h, hot 12 h', 'Cold 36 h, hot 18 h']], ['Lid', ['Leak-proof screw', 'Flip straw']], ['Weight', ['300 g', '410 g']]],
        features: ['Double-wall vacuum insulation', 'BPA-free lid', 'Fits most cup holders', 'Powder-coated grip', 'Dishwasher-safe lid'],
        variants: [['Size', ['500 ml', '750 ml', '1 L']], ['Color', ['Black', 'Sage', 'Navy', 'White', 'Coral']]] }),
      t('sleeping-bag', 'Sleeping Bag', { q: 'sleeping bag', must: ['sleeping bag', 'camping', 'tent'], price: [29, 179],
        uses: ['campsites', 'sleepovers', 'cabin trips'], series: ['Nest', 'Doze', 'Roll', 'Warm'],
        specs: [['Comfort rating', ['10 °C', '0 °C', '-5 °C']], ['Shape', ['Mummy', 'Rectangular']], ['Fill', ['Hollow-fiber synthetic', 'Recycled down']], ['Packed size', ['Compression sack included']], ['Weight', ['1.1 kg', '1.6 kg', '2.0 kg']]],
        features: ['Draft collar and hood', 'Zipper guard prevents snags', 'Compression sack included', 'Water-resistant shell', 'Two-way zipper'],
        variants: [['Rating', ['10 °C', '0 °C', '-5 °C']]] }),
    ] },
    'team-sports': { count: 25, types: [
      t('basketball', 'Basketball', { q: 'basketball', must: ['basketball', 'ball'], price: [12, 59],
        uses: ['street courts', 'gym practice', 'school teams'], series: ['Court', 'Hoop', 'Dunk', 'Pro'],
        specs: [['Size', ['Size 5', 'Size 6', 'Size 7']], ['Cover', ['Composite leather', 'Rubber']], ['Use', ['Indoor/outdoor', 'Indoor']], ['Weight', ['480 g', '567 g', '620 g']]],
        features: ['Deep channels for better grip', 'Consistent bounce', 'Wear-resistant outdoor cover', 'Pre-inflated', 'Official size and weight'],
        variants: [['Size', ['Size 5', 'Size 6', 'Size 7']]] }),
      t('soccer-ball', 'Soccer Ball', { q: 'soccer ball', must: ['soccer', 'football', 'ball'], price: [10, 59],
        uses: ['pickup games', 'training', 'school teams'], series: ['Strike', 'Goal', 'Pitch', 'Kick'],
        specs: [['Size', ['Size 3', 'Size 4', 'Size 5']], ['Construction', ['Machine-stitched', 'Thermal-bonded']], ['Cover', ['PU leather', 'TPU']], ['Weight', ['350 g', '410-450 g']]],
        features: ['Thermal-bonded for water resistance', 'Butyl bladder holds air longer', 'True flight', 'Soft touch cover', 'Pump needle included'],
        variants: [['Size', ['Size 3', 'Size 4', 'Size 5']]] }),
      t('volleyball', 'Volleyball', { q: 'volleyball', must: ['volleyball', 'ball'], price: [10, 55],
        uses: ['beach games', 'gym nights', 'team practice'], series: ['Spike', 'Net', 'Set', 'Sand'],
        specs: [['Size', ['Official size 5']], ['Cover', ['Soft composite leather', 'Waterproof PU']], ['Use', ['Indoor', 'Beach', 'Indoor/outdoor']], ['Weight', ['260 g', '280 g']]],
        features: ['Soft touch to protect forearms', 'Water-resistant cover', 'Stitched panels for consistent flight', 'Pre-inflated', 'Bright, visible panels'],
        variants: [['Style', ['Classic', 'Beach', 'Indoor']]] }),
    ] },
  },
  groceries: {
    beverages: { count: 30, types: [
      t('coffee-beans', 'Whole Bean Coffee', { q: 'coffee beans', must: ['coffee', 'beans'], price: [8, 29],
        uses: ['morning brews', 'espresso machines', 'pour-over'], series: ['Roast', 'Bean', 'Ridge', 'Dawn'],
        specs: [['Roast', ['Light', 'Medium', 'Medium dark', 'Dark']], ['Origin', ['Ethiopia', 'Colombia', 'Guatemala', 'Sumatra']], ['Weight', ['250 g', '500 g', '1 kg']], ['Process', ['Washed', 'Natural']], ['Tasting notes', ['Berry and cocoa', 'Caramel and citrus', 'Nutty and dark chocolate']]],
        features: ['Roasted in small batches', 'Resealable one-way valve bag', 'Ethically sourced beans', 'Roast date printed on the bag', 'Suits grinders and espresso machines'],
        variants: [['Size', ['250 g', '500 g', '1 kg']]] }),
      t('loose-tea', 'Loose-Leaf Tea', { q: 'loose leaf tea', must: ['tea'], price: [6, 24],
        uses: ['calm evenings', 'afternoon breaks', 'gifting'], series: ['Leaf', 'Brew', 'Steep', 'Garden'],
        specs: [['Type', ['Green tea', 'Black tea', 'Oolong', 'Herbal blend', 'White tea']], ['Weight', ['50 g', '100 g', '200 g']], ['Servings', ['25', '50', '100']], ['Caffeine', ['Low', 'Medium', 'Caffeine free']], ['Origin', ['Japan', 'India', 'Sri Lanka', 'China']]],
        features: ['Whole leaves, no dust', 'Resealable pouch', 'Steeps up to three times', 'Naturally flavored', 'Vegan and gluten free'],
        variants: [['Size', ['50 g', '100 g', '200 g']]] }),
      t('cold-brew', 'Cold Brew Coffee', { q: 'iced coffee bottle', must: ['coffee', 'iced', 'bottle', 'cold brew'], price: [3, 18],
        uses: ['hot mornings', 'desk breaks', 'road trips'], series: ['Chill', 'Cold', 'Ice', 'Brew'],
        specs: [['Volume', ['330 ml', '500 ml', '1 L']], ['Caffeine', ['120 mg per bottle', '200 mg per bottle']], ['Sugar', ['Unsweetened', 'Lightly sweetened']], ['Shelf life', ['Refrigerate; 45 days unopened']]],
        features: ['Steeped for 18 hours', 'Smooth and low in acidity', 'No artificial flavors', 'Ready to drink', 'Recyclable bottle'],
        variants: [['Pack', ['Single', '6-pack', '12-pack']]] }),
    ] },
    pantry: { count: 30, types: [
      t('olive-oil', 'Extra Virgin Olive Oil', { q: 'olive oil bottle', must: ['olive', 'oil'], price: [8, 39],
        uses: ['salads', 'roasting', 'dipping'], series: ['Grove', 'Press', 'Golden', 'Estate'],
        specs: [['Volume', ['500 ml', '750 ml', '1 L']], ['Origin', ['Spain', 'Italy', 'Greece']], ['Acidity', ['Below 0.4%', 'Below 0.3%']], ['Process', ['Cold pressed']], ['Container', ['Dark glass', 'Tin']]],
        features: ['Cold-pressed within hours of harvest', 'Dark glass protects flavor', 'Peppery, fruity finish', 'Harvest date on label', 'Single-estate olives'],
        variants: [['Size', ['500 ml', '750 ml', '1 L']]] }),
      t('pasta', 'Artisan Pasta', { q: 'dry pasta', must: ['pasta', 'spaghetti', 'noodle', 'penne'], price: [2, 12],
        uses: ['weeknight dinners', 'family meals', 'meal prep'], series: ['Nonna', 'Durum', 'Mill', 'Piazza'],
        specs: [['Weight', ['500 g', '1 kg']], ['Wheat', ['Durum semolina', 'Whole wheat', 'Organic durum']], ['Cook time', ['8 minutes', '10 minutes', '12 minutes']], ['Shape', ['Spaghetti', 'Penne', 'Fusilli', 'Rigatoni']], ['Process', ['Bronze-cut']]],
        features: ['Bronze-cut for sauce that clings', 'Slow-dried', 'Holds its bite', 'No additives', 'Resealable packaging'],
        variants: [['Shape', ['Spaghetti', 'Penne', 'Fusilli', 'Rigatoni']]] }),
      t('honey', 'Raw Honey', { q: 'honey jar', must: ['honey'], price: [5, 25],
        uses: ['tea', 'toast', 'baking'], series: ['Hive', 'Bloom', 'Golden', 'Meadow'],
        specs: [['Weight', ['250 g', '500 g', '1 kg']], ['Type', ['Wildflower', 'Clover', 'Orange blossom', 'Acacia']], ['Process', ['Raw, unfiltered']], ['Texture', ['Liquid', 'Creamy']], ['Container', ['Glass jar']]],
        features: ['Raw and unheated', 'Single-region harvest', 'No added sugar', 'Glass jar with a reusable lid', 'Naturally crystallizes over time'],
        variants: [['Size', ['250 g', '500 g', '1 kg']]] }),
      t('granola', 'Crunchy Granola', { q: 'granola bowl', must: ['granola', 'oats', 'cereal', 'muesli'], price: [4, 14],
        uses: ['breakfast bowls', 'snacking', 'yogurt toppings'], series: ['Oat', 'Crunch', 'Harvest', 'Morning'],
        specs: [['Weight', ['300 g', '500 g', '800 g']], ['Base', ['Rolled oats', 'Oats and seeds']], ['Sweetener', ['Maple syrup', 'Honey', 'No added sugar']], ['Allergens', ['Contains nuts', 'Nut free']], ['Protein', ['8 g per serving', '10 g per serving']]],
        features: ['Baked in small batches', 'Big, crunchy clusters', 'No artificial flavors', 'Resealable pouch', 'Plant-based'],
        variants: [['Flavor', ['Maple Almond', 'Honey Oat', 'Cocoa Hazelnut', 'Berry Seed']]] }),
    ] },
    fresh: { count: 20, types: [
      t('apples', 'Orchard Apples', { q: 'fresh apples', must: ['apple', 'apples'], price: [3, 12],
        uses: ['snacking', 'baking', 'lunchboxes'], series: ['Orchard', 'Crisp', 'Harvest', 'Grove'],
        specs: [['Variety', ['Gala', 'Fuji', 'Honeycrisp', 'Granny Smith']], ['Weight', ['1 kg', '2 kg', '3 kg']], ['Origin', ['Regional orchards']], ['Grade', ['Class I']], ['Storage', ['Refrigerate up to 4 weeks']]],
        features: ['Picked at peak ripeness', 'Crisp and juicy', 'Sorted by hand', 'Pesticide-residue tested', 'Packed in recyclable cartons'],
        variants: [['Size', ['1 kg', '2 kg', '3 kg']]] }),
      t('avocados', 'Ripe Avocados', { q: 'avocado', must: ['avocado'], price: [3, 14],
        uses: ['toast', 'salads', 'guacamole'], series: ['Green', 'Ripe', 'Haas', 'Creamy'],
        specs: [['Variety', ['Hass']], ['Count', ['3', '4', '6']], ['Ripeness', ['Ready to eat', 'Ready in 2-3 days']], ['Origin', ['Mexico', 'Peru', 'Spain']], ['Storage', ['Refrigerate once ripe']]],
        features: ['Creamy, buttery flesh', 'Graded for consistent size', 'Sorted by ripeness', 'Rich in healthy fats', 'No packaging waste inside'],
        variants: [['Count', ['3 pack', '4 pack', '6 pack']]] }),
      t('tomatoes', 'Vine Tomatoes', { q: 'fresh tomatoes', must: ['tomato', 'tomatoes'], price: [2, 10],
        uses: ['salads', 'pasta sauce', 'sandwiches'], series: ['Vine', 'Ruby', 'Garden', 'Sun'],
        specs: [['Variety', ['Vine', 'Cherry', 'Beefsteak', 'Roma']], ['Weight', ['500 g', '1 kg']], ['Origin', ['Regional greenhouse']], ['Grade', ['Class I']], ['Storage', ['Keep at room temperature']]],
        features: ['Ripened on the vine', 'Sweet and full of flavor', 'Pesticide-residue tested', 'Sorted by hand', 'Fresh from regional growers'],
        variants: [['Type', ['Vine', 'Cherry', 'Beefsteak']]] }),
    ] },
  },
  accessories: {
    watches: { count: 30, types: [
      t('analog-watch', 'Analog Wristwatch', { q: 'wristwatch', must: ['watch', 'wristwatch'], price: [29, 299],
        uses: ['office days', 'special occasions', 'daily wear'], series: ['Classic', 'Heritage', 'Meridian', 'Dial'],
        specs: [['Case size', ['36 mm', '40 mm', '42 mm']], ['Movement', ['Japanese quartz', 'Automatic']], ['Glass', ['Sapphire-coated', 'Mineral crystal']], ['Water resistance', ['3 ATM', '5 ATM']], ['Strap', ['Genuine leather', 'Stainless steel mesh', 'Stainless steel link']]],
        features: ['Slim profile', 'Luminous hands', 'Quick-release strap', 'Scratch-resistant glass', 'Gift box included'],
        variants: [['Dial', ['Black', 'Silver', 'Navy', 'Green']], ['Strap', ['Leather', 'Steel']]] }),
      t('digital-watch', 'Digital Sports Watch', { q: 'digital watch', must: ['watch', 'digital'], price: [19, 149],
        uses: ['running', 'swimming', 'outdoor trips'], series: ['Sport', 'Pulse', 'Tough', 'Lap'],
        specs: [['Case size', ['44 mm', '47 mm']], ['Display', ['LCD with backlight']], ['Battery', ['10-year cell', 'Solar']], ['Water resistance', ['10 ATM']], ['Functions', ['Stopwatch, alarm, dual time', 'Stopwatch, timer, world time']]],
        features: ['Shock-resistant case', 'LED backlight', 'Daily alarm and hourly chime', 'Soft resin strap', 'Long-life battery'],
        variants: [['Color', ['Black', 'Blue', 'Red', 'Green']]] }),
    ] },
    jewelry: { count: 25, types: [
      t('necklace', 'Pendant Necklace', { q: 'necklace jewelry', must: ['necklace', 'pendant', 'jewelry', 'jewellery'], price: [14, 129],
        uses: ['everyday wear', 'gifts', 'special occasions'], series: ['Charm', 'Pendant', 'Gleam', 'Link'],
        specs: [['Material', ['Sterling silver', '14k gold-plated brass', 'Stainless steel']], ['Chain length', ['40 cm + 5 cm extender', '45 cm + 5 cm extender']], ['Pendant size', ['12 mm', '15 mm', '18 mm']], ['Clasp', ['Lobster']], ['Finish', ['Polished', 'Brushed']]],
        features: ['Hypoallergenic metals', 'Tarnish-resistant coating', 'Adjustable length', 'Gift pouch included', 'Lightweight for all-day wear'],
        variants: [['Finish', ['Silver', 'Gold', 'Rose Gold']]] }),
      t('bracelet', 'Charm Bracelet', { q: 'bracelet jewelry', must: ['bracelet', 'jewelry', 'jewellery', 'bangle'], price: [12, 99],
        uses: ['daily wear', 'gifting', 'layering'], series: ['Bangle', 'Link', 'Cuff', 'Charm'],
        specs: [['Material', ['Sterling silver', 'Gold-plated brass', 'Stainless steel']], ['Length', ['16 cm + 4 cm extender', '18 cm + 3 cm extender']], ['Width', ['3 mm', '5 mm', '8 mm']], ['Clasp', ['Lobster', 'Toggle']]],
        features: ['Nickel-free', 'Water-safe finish', 'Stackable design', 'Adjustable fit', 'Gift pouch included'],
        variants: [['Finish', ['Silver', 'Gold', 'Rose Gold']]] }),
      t('earrings', 'Stud Earrings', { q: 'earrings jewelry', must: ['earring', 'jewelry', 'jewellery'], price: [8, 79],
        uses: ['daily wear', 'sensitive ears', 'gifting'], series: ['Stud', 'Hoop', 'Drop', 'Gem'],
        specs: [['Material', ['Sterling silver', '14k gold-plated', 'Titanium posts']], ['Size', ['6 mm', '8 mm', '10 mm']], ['Back', ['Butterfly', 'Screw back']], ['Finish', ['Polished']]],
        features: ['Hypoallergenic posts', 'Lightweight and comfortable', 'Tarnish-resistant', 'Gift box included', 'Pair of two'],
        variants: [['Finish', ['Silver', 'Gold', 'Rose Gold']]] }),
    ] },
    'small-goods': { count: 25, types: [
      t('wallet', 'Leather Wallet', { q: 'leather wallet', must: ['wallet'], price: [19, 99],
        uses: ['daily carry', 'travel', 'gifts'], series: ['Fold', 'Slim', 'Card', 'Craft'],
        specs: [['Material', ['Full-grain leather', 'Top-grain leather', 'Vegan leather']], ['Card slots', ['6', '8', '10']], ['Dimensions', ['11 x 9 x 2 cm', '12 x 10 x 2 cm']], ['Closure', ['Bifold', 'Trifold']], ['Extras', ['RFID-blocking lining']]],
        features: ['RFID-blocking lining', 'Hand-stitched edges', 'Coin pocket', 'Gift box included', 'Develops a patina over time'],
        variants: [['Color', ['Black', 'Brown', 'Tan', 'Navy']]] }),
      t('card-holder', 'Slim Card Holder', { q: 'card holder wallet', must: ['wallet', 'card', 'holder'], price: [9, 49],
        uses: ['minimal carry', 'travel', 'daily errands'], series: ['Slim', 'Card', 'Pocket', 'Fold'],
        specs: [['Material', ['Leather', 'Aluminum', 'Vegan leather']], ['Capacity', ['4-6 cards', '6-8 cards']], ['Dimensions', ['10 x 7 x 0.8 cm']], ['Extras', ['RFID-blocking']]],
        features: ['Fits in a front pocket', 'RFID-blocking', 'Quick-access thumb slot', 'Holds folded bills', 'Gift box included'],
        variants: [['Color', ['Black', 'Brown', 'Grey', 'Green']]] }),
      t('belt', 'Leather Belt', { q: 'leather belt', must: ['belt'], price: [14, 79],
        uses: ['office wear', 'denim', 'daily outfits'], series: ['Belt', 'Strap', 'Buckle', 'Edge'],
        specs: [['Material', ['Full-grain leather', 'Genuine leather', 'Vegan leather']], ['Width', ['3 cm', '3.5 cm']], ['Buckle', ['Brushed steel', 'Matte black']], ['Sizes', ['Fits 28-44" waists']]],
        features: ['Solid metal buckle', 'Edge-finished leather', 'Fits between holes for a custom fit', 'Gift box included', 'Reversible black and brown'],
        variants: [['Size', ['S', 'M', 'L', 'XL']], ['Color', ['Black', 'Brown', 'Tan']]] }),
    ] },
    travel: { count: 20, types: [
      t('suitcase', 'Carry-On Suitcase', { q: 'carry on suitcase', must: ['suitcase', 'luggage'], price: [49, 249],
        uses: ['weekend trips', 'business travel', 'airline carry-on'], series: ['Roll', 'Jet', 'Carry', 'Voyage'],
        specs: [['Capacity', ['35 L', '40 L', '45 L']], ['Dimensions', ['55 x 35 x 23 cm', '56 x 36 x 23 cm']], ['Shell', ['Polycarbonate', 'ABS and PC']], ['Wheels', ['360° spinner']], ['Lock', ['TSA-approved combination lock']]],
        features: ['Fits most airline carry-on limits', 'Expandable section', 'Quiet spinner wheels', 'Telescoping aluminum handle', 'Interior compression straps'],
        variants: [['Color', ['Black', 'Navy', 'Silver', 'Teal']]] }),
      t('packing-cubes', 'Packing Cubes Set', { q: 'packing cubes', must: ['packing', 'cube', 'luggage', 'suitcase', 'travel'], price: [9, 49],
        uses: ['organizing suitcases', 'carry-on trips', 'weekends away'], series: ['Pack', 'Cube', 'Fold', 'Neat'],
        specs: [['Pieces', ['4', '6']], ['Material', ['Ripstop nylon', 'Recycled polyester']], ['Sizes', ['S, M, L, XL']], ['Weight', ['280 g', '350 g']]],
        features: ['Double zippers', 'Mesh top for easy viewing', 'Compresses clothing', 'Machine washable', 'Laundry bag included'],
        variants: [['Color', ['Grey', 'Navy', 'Teal', 'Coral']]] }),
      t('travel-pillow', 'Memory Foam Travel Pillow', { q: 'travel neck pillow', must: ['pillow', 'neck', 'travel'], price: [9, 49],
        uses: ['long flights', 'road trips', 'train rides'], series: ['Rest', 'Neck', 'Wrap', 'Drift'],
        specs: [['Fill', ['Memory foam', 'Microbead']], ['Cover', ['Velour', 'Cotton', 'Bamboo']], ['Weight', ['280 g', '350 g']], ['Care', ['Cover machine washable']]],
        features: ['Supports the head and neck', 'Removable washable cover', 'Compresses into a carry bag', 'Clip to attach to luggage', 'Breathable fabric'],
        variants: [['Color', ['Grey', 'Navy', 'Burgundy', 'Teal']]] }),
    ] },
  },
};

export const CATEGORY_NAMES = {
  electronics: 'Electronics', fashion: 'Fashion', beauty: 'Beauty', home: 'Home',
  sports: 'Sports', groceries: 'Groceries', accessories: 'Accessories',
};

/* Category/subcategory → target count, e.g. { electronics: { audio: 40, ... } }. */
export function targetCounts() {
  const out = {};
  for (const cat of Object.keys(TAXONOMY)) {
    out[cat] = {};
    for (const sub of Object.keys(TAXONOMY[cat])) out[cat][sub] = TAXONOMY[cat][sub].count;
  }
  return out;
}

export function totalTarget() {
  return Object.values(targetCounts()).reduce((n, c) => n + Object.values(c).reduce((a, b) => a + b, 0), 0);
}
